<?php

namespace App\Repository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByEmail($email)
    {
        $qb = $this->createQueryBuilder('m')
        ->where('m.email = :email')
        ->setParameter('email', $email);
        return $qb->getQuery()->setMaxResults(1)->getOneOrNullResult();
    }
    public function getByName($firstname, $lastname)
    {
        $qb = $this->createQueryBuilder('m')
        ->where('m.firstname = :firstname')
        ->andWhere('m.lastname = :lastname')
        ->setParameter('firstname', $firstname)
        ->setParameter('lastname', $lastname);
        return $qb->getQuery()->setMaxResults(1)->getOneOrNullResult();
    }
    public function countByActiveMember()
    {
        $qb = $this->createQueryBuilder('m');
        $qb->select($qb->expr()->count('m'))
        ->where('m.isActiveMember = :is')
        ->setParameter('is', true);
        return $qb->getQuery()->getSingleScalarResult();
    }
    public function countByMember()
    {
        $qb = $this->createQueryBuilder('m');
        $qb->select($qb->expr()->count('m'));
        return $qb->getQuery()->getSingleScalarResult();
    }
}
