knpu_oauth2_client:
    clients:
        mattermost:
            # must be "slack" - it activates that type!
            type: generic
            provider_class: Entropy\TunkkiBundle\Provider\Mattermost
            # add and configure client_id and client_secret in parameters.yml
            client_id: %mattermost_client_id%
            client_secret: %mattermost_client_secret%
            # a route name you'll create
            redirect_route: _entropy_mattermost_check
            redirect_params: {}

            # whether to check OAuth2 "state": defaults to true
            # use_state: false
