version: 2
updates:
  - package-ecosystem: docker
    directory: /docker/fpm
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/web
    schedule:
      interval: daily
