services:
  db:
    image: mariadb:${DB_IMAGE_VERSION}
    restart: unless-stopped
    user: ${USERID}:${GROUPID}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - ./docker/data/db:/var/lib/mysql
  fpm:
    build:
      context: docker/fpm
      target: ${APP_ENV}
      args:
        UID: ${USERID}
        GID: ${GROUPID}
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV}
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:3306/${DB_NAME}?serverVersion=${DB_IMAGE_VERSION}-MariaDB"
    expose:
      - "9000"
    depends_on:
      - db
    volumes:
      - .:/var/www
      - /etc/localtime:/etc/localtime:ro
  web:
    build:
      context: docker/web
      args:
        UID: ${USERID}
        GID: ${GROUPID}
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-9090}:80"
    links:
      - fpm
    volumes:
      - ./symfony/public:/var/www/symfony/public
      - /etc/localtime:/etc/localtime:ro
  node:
    image: node:20-alpine
    volumes:
      - ./symfony:/app
    ports:
      - "${DEV_SERVER_PORT:-8080}:8080"
    working_dir: /app
    command: ["/bin/true"]
