version: '3.2'

networks:
    front-tier:
    back-tier:

services:
    fpm:
        build: docker/fpm
        restart: unless-stopped
        networks:
            - back-tier
        expose:
            - "9000"
        volumes:
            - ./symfony:/var/www/symfony
            - /etc/localtime:/etc/localtime:ro
    web:
        build: docker/web
        restart: unless-stopped
        networks:
            - back-tier
            - front-tier
        ports:
            - "3011:80"
        links:
            - fpm
        volumes:
            - ./symfony/public:/var/www/symfony/public
    node:
        image: node:16-alpine
        volumes:
            - ./symfony:/app
        ports:
            - "${DEV_SERVER_PORT:-8080}:8080"
        working_dir: /app
        command: ["/bin/true"]
