version: '3.2'

networks:
    front-tier:
    back-tier:

services:
    fpm:
        build: fpm
        restart: unless-stopped
        networks:
            - back-tier
        expose:
            - "9000"
        volumes:
            - ./symfony:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
            - /etc/localtime:/etc/localtime:ro
    web:
        build: web
        restart: unless-stopped
        networks:
            - back-tier
            - front-tier
        ports:
            - "3011:80"
        links:
            - fpm
        volumes:
            - ./symfony/web:/var/www/symfony/web
            - ./logs/nginx/:/var/log/nginx
