version: '3.2'

networks:
    front-tier:
    back-tier:

services:
    db:
        image: mariadb:${DB_IMAGE_VERSION}
        restart: unless-stopped
        networks:
            - back-tier
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./docker/data/db:/var/lib/mysql
    fpm:
        build: docker/fpm
        restart: unless-stopped
        environment:
            DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:3306/${DB_NAME}?serverVersion=mariadb-${DB_IMAGE_VERSION}"
        networks:
            - back-tier
        expose:
            - "9000"
        volumes:
            - .:/var/www
            - /etc/localtime:/etc/localtime:ro
    web:
        build: docker/web
        restart: unless-stopped
        networks:
            - back-tier
            - front-tier
        ports:
            - "3011:80"
        links:
            - fpm
        volumes:
            - ./symfony/public:/var/www/symfony/public
    node:
        image: node:16-alpine
        volumes:
            - ./symfony:/app
        ports:
            - "${DEV_SERVER_PORT:-8080}:8080"
        working_dir: /app
        command: ["/bin/true"]
