version: '2'
services:
    storage:
        image: debian:jessie
        volumes:
            - ./symfony:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    fpm:
        build: fpm
        expose:
            - "9000"
        volumes_from:
            - storage
    web:
        build: web
        ports:
            - "3011:80"
        links:
            - fpm
        volumes_from:
            - storage
        volumes:
            - ./logs/nginx/:/var/log/nginx
