version: '3.2'

networks:
    front-tier:
    back-tier:

services:
    #    storage:
    #    image: debian:jessie
    #    volumes:
    #        - ./symfony:/var/www/symfony
    #        - ./logs/symfony:/var/www/symfony/app/logs
    fpm:
        build: fpm
        restart: unless-stopped
        networks:
            - back-tier
        expose:
            - "9000"
        volumes:
            - ./symfony:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
    web:
        build: web
        restart: unless-stopped
        networks:
            - back-tier
            - front-tier
        ports:
            - "3011:80"
        links:
            - fpm
        volumes:
            - ./symfony:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
        volumes:
            - ./logs/nginx/:/var/log/nginx
