#entropy_tunkki_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: EntropyTunkkiBundle:Default:index }
_entropy_mattermost_auth:
    path:     /oauth
    defaults: { _controller: EntropyTunkkiBundle:MattermostAuth:connect }
_entropy_mattermost_check:
    path:     /oauth/check
    defaults: { _controller: EntropyTunkkiBundle:MattermostAuth:connectCheck }
_entropy_mattermost_check_ssl:
    path:     /oauth/check
    defaults: { _controller: EntropyTunkkiBundle:MattermostAuth:connectCheck }
    schemes:  [https]

