services:
    entropy_tunkki.helper.mattermost:
        class: Entropy\TunkkiBundle\Helper\Mattermost
        arguments: ["@service_container"]
    my_mattermost_authenticator:
        class: Entropy\TunkkiBundle\Security\MattermostAuthenticator
        #autowire: true
        # use autowiring, OR you can specify the argument manually
        arguments:
            - '@oauth2.registry'
            - '@doctrine.orm.entity_manager'
            - '@router'

    entropy_tunkki.admin.item:
        class: Entropy\TunkkiBundle\Admin\ItemAdmin
        arguments:
            - ~
            - Entropy\TunkkiBundle\Entity\Item
            - EntropyTunkkiBundle:ItemAdmin
            - "@entropy_tunkki.helper.mattermost"
            - "@security.token_storage"
            - "@sonata.classification.manager.context"
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Items }
        calls:
            - [setTemplate, [outer_list_rows_mosaic, EntropyTunkkiBundle:Admin:list_outer_rows_mosaic.html.twig]]
            - [setTemplate, [inner_list_row, EntropyTunkkiBundle:Admin:list_items.html.twig]]
            - [setTemplate, [base_list_field, SonataAdminBundle:CRUD:base_list_flat_field.html.twig]]
            - [addChild, ['@entropy_tunkki.admin.event']]
            - [addChild, ['@entropy_tunkki.admin.file']]

    entropy_tunkki.admin.event:
        class: Entropy\TunkkiBundle\Admin\EventAdmin
        arguments:
            - ~
            - Entropy\TunkkiBundle\Entity\Event
            - SonataAdminBundle:CRUD
            - "@entropy_tunkki.helper.mattermost"
            - "@security.token_storage"
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: All Events, show_mosaic_button: false  }

    entropy_tunkki.admin.file:
        class: Entropy\TunkkiBundle\Admin\FileAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\File, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: All Files, show_mosaic_button: false }

    entropy_tunkki.page.itempage:
        class: Entropy\TunkkiBundle\PageService\ItemPage
        arguments:
                - "Item history"
                - "@sonata.page.template_manager"
                - "@doctrine.orm.entity_manager"
        tags:
                - { name: sonata.page, alias: Item}

    entropy_tunkki.admin.booking:
        class: Entropy\TunkkiBundle\Admin\BookingAdmin
        arguments: 
            - ~
            - Entropy\TunkkiBundle\Entity\Booking
            - EntropyTunkkiBundle:BookingAdmin
            - "@entropy_tunkki.helper.mattermost"
            - "@security.token_storage"
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Bookings }
        calls:
            - [setTemplate, [inner_list_row, EntropyTunkkiBundle:Admin:list_bookings.html.twig]]
            - [setTemplate, [base_list_field, SonataAdminBundle:CRUD:base_list_flat_field.html.twig]]

    entropy_tunkki.admin.pakage:
        class: Entropy\TunkkiBundle\Admin\PakageAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\Pakage, EntropyTunkkiBundle:PakageAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Pakages }

    entropy_tunkki.admin.renter:
        class: Entropy\TunkkiBundle\Admin\RenterAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\Renter, EntropyTunkkiBundle:RenterAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Renters }

    entropy_tunkki.admin.billable_event:
        class: Entropy\TunkkiBundle\Admin\BillableEventAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\BillableEvent, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Billable Events }

    entropy_tunkki.block.bookings:
        class: Entropy\TunkkiBundle\Block\BookingsBlock
        arguments: # Nämä kaikki välitetään classin _construct functiolle
            - "Booking Block" # Tämä on blockin nimi adminissa
            - "@templating" # teplate
            - "@doctrine.orm.entity_manager" # Entity manager blockin käyttöön
            - "@service_container" # service container
        tags:
            - { name: sonata.block, alias: bookingblock }

    entropy_tunkki.admin.who_can_rent_choice:
        class: Entropy\TunkkiBundle\Admin\WhoCanRentChoiceAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\WhoCanRentChoice, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: WhoCanRentChoices }

    entropy_tunkki.admin.accessory:
        class: Entropy\TunkkiBundle\Admin\AccessoryAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\Accessory, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Accessory }
        public: true

    entropy_tunkki.admin.accessory_choices:
        class: Entropy\TunkkiBundle\Admin\AccessoryChoiceAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\AccessoryChoice, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: AccessoryChoices }
        public: true
