services:
    entropy_tunkki.helper.mattermost:
        class: Entropy\TunkkiBundle\Helper\Mattermost
        arguments: ["@service_container"]
    my_mattermost_authenticator:
        class: Entropy\TunkkiBundle\Security\MattermostAuthenticator
        #autowire: true
        # use autowiring, OR you can specify the argument manually
        arguments:
            - '@oauth2.registry'
            - '@doctrine.orm.entity_manager'
            - '@router'
    entropy_tunkki.form.type.items:
        class: Entropy\TunkkiBundle\Form\Type\ItemsType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sonata.classification.manager.category'
        tags:
            - { name: form.type }
    entropy_tunkki.form.type.packages:
        class: Entropy\TunkkiBundle\Form\Type\PackagesType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    entropy_tunkki.admin.item:
        class: Entropy\TunkkiBundle\Admin\ItemAdmin
        arguments:
            - ~
            - Entropy\TunkkiBundle\Entity\Item
            - EntropyTunkkiBundle:ItemAdmin
            - "@entropy_tunkki.helper.mattermost"
            - "@security.token_storage"
            - "@sonata.classification.manager.context"
        tags:
            - { name: sonata.admin, manager_type: orm, audit: true, group: admin, label: Items }
        calls:
            - [setTemplate, [outer_list_rows_mosaic, EntropyTunkkiBundle:Admin:list_outer_rows_mosaic.html.twig]]
            - [setTemplate, [inner_list_row, EntropyTunkkiBundle:Admin:list_items.html.twig]]
            - [setTemplate, [base_list_field, SonataAdminBundle:CRUD:base_list_flat_field.html.twig]]
            - [addChild, ['@entropy_tunkki.admin.event'], ['item']]
            - [addChild, ['@entropy_tunkki.admin.file'], ['files']]
        public: true

    entropy_tunkki.admin.event:
        class: Entropy\TunkkiBundle\Admin\EventAdmin
        arguments:
            - ~
            - Entropy\TunkkiBundle\Entity\Event
            - SonataAdminBundle:CRUD
            - "@entropy_tunkki.helper.mattermost"
            - "@security.token_storage"
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Item Events, show_mosaic_button: false  }
        public: true

    entropy_tunkki.admin.user:
        class: Entropy\TunkkiBundle\Admin\UserAdmin
        arguments:
            - ~
            - Application\Sonata\UserBundle\Entity\User
            - SonataAdminBundle:CRUD
            - "@entropy_tunkki.helper.mattermost"
            - "@security.token_storage"
        tags:
            - { name: sonata.admin, manager_type: orm, audit: true, group: admin, label: users, show_mosaic_button: false  }
        public: true

    entropy_tunkki.admin.file:
        class: Entropy\TunkkiBundle\Admin\FileAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\File, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Files, show_mosaic_button: false }
        public: true

    entropy_tunkki.page.itempage:
        class: Entropy\TunkkiBundle\PageService\ItemPage
        arguments:
                - "Item history"
                - "@sonata.page.template_manager"
                - "@doctrine.orm.entity_manager"
        tags:
                - { name: sonata.page, alias: Item}
        public: true

    entropy_tunkki.admin.booking:
        class: Entropy\TunkkiBundle\Admin\BookingAdmin
        arguments: 
            - ~
            - Entropy\TunkkiBundle\Entity\Booking
            - EntropyTunkkiBundle:BookingAdmin
            - "@entropy_tunkki.helper.mattermost"
            - "@security.token_storage"
            - "@doctrine.orm.entity_manager"
            - "@sonata.classification.manager.category"
        tags:
            - { name: sonata.admin, manager_type: orm, audit: true, group: admin, label: Bookings, show_mosaic_button: false }
        calls:
            - [setTemplate, [inner_list_row, EntropyTunkkiBundle:Admin:list_bookings.html.twig]]
            - [setTemplate, [base_list_field, SonataAdminBundle:CRUD:base_list_flat_field.html.twig]]
            - [addChild, ['@entropy_tunkki.admin.event'], ['booking']]
        public: true

    entropy_tunkki.admin.package:
        class: Entropy\TunkkiBundle\Admin\PackageAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\Package, EntropyTunkkiBundle:PackageAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Packages }
        public: true

    entropy_tunkki.admin.renter:
        class: Entropy\TunkkiBundle\Admin\RenterAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\Renter, EntropyTunkkiBundle:RenterAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Renters }
        public: true

    entropy_tunkki.admin.billable_event:
        class: Entropy\TunkkiBundle\Admin\BillableEventAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\BillableEvent, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Billable Events }
        public: true

    entropy_tunkki.block.bookings:
        class: Entropy\TunkkiBundle\Block\BookingsBlock
        arguments: # Nämä kaikki välitetään classin _construct functiolle
            - "Booking Block" # Tämä on blockin nimi adminissa
            - "@templating" # teplate
            - "@doctrine.orm.entity_manager" # Entity manager blockin käyttöön
        tags:
            - { name: sonata.block, alias: bookingblock }

    entropy_tunkki.block.brokenitems:
        class: Entropy\TunkkiBundle\Block\BrokenItemsBlock
        arguments: # Nämä kaikki välitetään classin _construct functiolle
            - "Broken Items Block" # Tämä on blockin nimi adminissa
            - "@templating" # teplate
            - "@doctrine.orm.entity_manager" # Entity manager blockin käyttöön
        tags:
            - { name: sonata.block, alias: brokenitemsblock }

    entropy_tunkki.admin.who_can_rent_choice:
        class: Entropy\TunkkiBundle\Admin\WhoCanRentChoiceAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\WhoCanRentChoice, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: WhoCanRentChoices }
        public: true

    entropy_tunkki.admin.accessory:
        class: Entropy\TunkkiBundle\Admin\AccessoryAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\Accessory, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Accessory }
        public: true

    entropy_tunkki.admin.accessory_choices:
        class: Entropy\TunkkiBundle\Admin\AccessoryChoiceAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\AccessoryChoice, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: AccessoryChoices }
        public: true

    entropy_tunkki.admin.email_notification:
        class: Entropy\TunkkiBundle\EventListener\BookingAdminListener
        arguments:
            - "@swiftmailer.mailer"
            - "@templating"
            - "%booking_notification_email%"
            - "%mm_tunkki_img%"
        tags:
            - { name: kernel.event_listener, event: sonata.admin.event.persistence.post_persist, method: sendEmailNotification }
