services:
#    entropy_tunkki.example:
#        class: Entropy\TunkkiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    entropy_tunkki.admin.events:
        class: Entropy\TunkkiBundle\Admin\EventAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\Event, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Item Events, show_mosaic_button: false  }

    entropy_tunkki.admin.items:
        class: Entropy\TunkkiBundle\Admin\ItemAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\Item, EntropyTunkkiBundle:ItemAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Items }
        calls:
            - [setTemplate, [outer_list_rows_mosaic, EntropyTunkkiBundle:Admin:list_outer_rows_mosaic.html.twig]]

    entropy_tunkki.admin.files:
        class: Entropy\TunkkiBundle\Admin\FileAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\File, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Files, show_mosaic_button: false }

    entropy_tunkki.page.itempage:
        class: Entropy\TunkkiBundle\PageService\ItemPage
        arguments:
                - "Item history"
                - "@sonata.page.template_manager"
                - "@doctrine.orm.entity_manager"
        tags:
                - { name: sonata.page, alias: Item}

    entropy_tunkki.admin.booking:
        class: Entropy\TunkkiBundle\Admin\BookingAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\Booking, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Bookings }

    entropy_tunkki.admin.pakage:
        class: Entropy\TunkkiBundle\Admin\PakageAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\Pakage, EntropyTunkkiBundle:PakageAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Pakage }

    entropy_tunkki.admin.invoicee:
        class: Entropy\TunkkiBundle\Admin\InvoiceeAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\Invoicee, EntropyTunkkiBundle:InvoiceeAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Invoicee }
