services:
#    entropy_tunkki.example:
#        class: Entropy\TunkkiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    entropy_tunkki.admin.events:
        class: Entropy\TunkkiBundle\Admin\EventAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\Event, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Events }

    entropy_tunkki.admin.items:
        class: Entropy\TunkkiBundle\Admin\ItemAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\Item, EntropyTunkkiBundle:ItemAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Items }
        calls:
            - [setTemplate, [outer_list_rows_mosaic, EntropyTunkkiBundle:Admin:list_outer_rows_mosaic.html.twig]]

    entropy_tunkki.admin.files:
        class: Entropy\TunkkiBundle\Admin\FileAdmin
        arguments: [~, Entropy\TunkkiBundle\Entity\File, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Files }
