<?php

namespace Entropy\TunkkiBundle\Entity;

/**
 * BillableEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillableEventRepository extends \Doctrine\ORM\EntityRepository
{
}
