<?php

namespace Entropy\TunkkiBundle\Entity;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
	public function findBookingsAtTheSameTime($id, $startAt, $endAt)
	{
		$queryBuilder = $this->createQueryBuilder('b')
					   ->andWhere('b.retrieval BETWEEN :startAt and :endAt')
					   ->orWhere('b.returning BETWEEN :startAt and :endAt')
					   ->andWhere('b.itemsReturned = false')
					   ->andWhere('b.id != :id')
					   ->setParameter('startAt', $startAt)
					   ->setParameter('endAt', $endAt)
					   ->setParameter('id', $id)
					   ->orderBy('b.name', 'ASC');
		return $queryBuilder->getQuery()->getResult();
	}
}
