<?php

namespace Entropy\TunkkiBundle\Entity;

/**
 * InvoiceeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceeRepository extends \Doctrine\ORM\EntityRepository
{
}
