<?php

namespace Entropy\TunkkiBundle\Entity;

/**
 * VarastoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemsRepository extends \Doctrine\ORM\EntityRepository
{
}
