<?php

namespace Entropy\TunkkiBundle\Entity;

/**
 * PackagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackagesRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPackageChoicesWithPrivileges($privileges)
	{
		$queryBuilder = $this->createQueryBuilder('p')
				   ->andWhere('p.rent >= 0.00')
				   ->leftJoin('p.whoCanRent', 'r')
				   ->andWhere('r = :privilege')
				   ->setParameter('privilege', $privileges)
				   ->orderBy('p.name', 'ASC');
		return $queryBuilder->getQuery()->getResult();
	}
}
