<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20191217163632 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE acl_entries DROP FOREIGN KEY FK_46C8B806EA000B10');
        $this->addSql('ALTER TABLE acl_entries DROP FOREIGN KEY FK_46C8B8063D9AB4A6');
        $this->addSql('ALTER TABLE acl_object_identities DROP FOREIGN KEY FK_9407E54977FA751A');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors DROP FOREIGN KEY FK_825DE2993D9AB4A6');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors DROP FOREIGN KEY FK_825DE299C671CEA1');
        $this->addSql('ALTER TABLE acl_entries DROP FOREIGN KEY FK_46C8B806DF9183C9');
        $this->addSql('DROP TABLE AccessoryChoice_audit');
        $this->addSql('DROP TABLE Accessory_audit');
        $this->addSql('DROP TABLE BillableEvent_audit');
        $this->addSql('DROP TABLE Event_audit');
        $this->addSql('DROP TABLE File_audit');
        $this->addSql('DROP TABLE Package_audit');
        $this->addSql('DROP TABLE Pakage_tags');
        $this->addSql('DROP TABLE Renter_audit');
        $this->addSql('DROP TABLE WhoCanRentChoice_audit');
        $this->addSql('DROP TABLE acl_classes');
        $this->addSql('DROP TABLE acl_entries');
        $this->addSql('DROP TABLE acl_object_identities');
        $this->addSql('DROP TABLE acl_object_identity_ancestors');
        $this->addSql('DROP TABLE acl_security_identities');
        $this->addSql('DROP TABLE classification__category_audit');
        $this->addSql('DROP TABLE classification__collection_audit');
        $this->addSql('DROP TABLE classification__context_audit');
        $this->addSql('DROP TABLE classification__tag_audit');
        $this->addSql('DROP TABLE file_item');
        $this->addSql('DROP TABLE fos_user_group_audit');
        $this->addSql('DROP TABLE fos_user_user_audit');
        $this->addSql('DROP TABLE media__gallery_audit');
        $this->addSql('DROP TABLE media__gallery_media_audit');
        $this->addSql('DROP TABLE media__media_audit');
        $this->addSql('DROP TABLE member_audit');
        $this->addSql('DROP TABLE notification__message_audit');
        $this->addSql('DROP TABLE page__block_audit');
        $this->addSql('DROP TABLE page__page_audit');
        $this->addSql('DROP TABLE page__site_audit');
        $this->addSql('DROP TABLE page__snapshot_audit');
        $this->addSql('ALTER TABLE Package CHANGE name name VARCHAR(190) NOT NULL, CHANGE rent rent VARCHAR(190) NOT NULL');
        $this->addSql('ALTER TABLE package_who_can_rent_choice DROP FOREIGN KEY FK_48FF341E9D9A436');
        $this->addSql('DROP INDEX IDX_48FF341E9D9A436 ON package_who_can_rent_choice');
        $this->addSql('ALTER TABLE package_who_can_rent_choice DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE package_who_can_rent_choice DROP FOREIGN KEY FK_48FF341F44CABFF');
        $this->addSql('ALTER TABLE package_who_can_rent_choice CHANGE whocanrentchoice_id who_can_rent_choice_id INT NOT NULL');
        $this->addSql('ALTER TABLE package_who_can_rent_choice ADD CONSTRAINT FK_27443592B44A2EEE FOREIGN KEY (who_can_rent_choice_id) REFERENCES WhoCanRentChoice (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_27443592B44A2EEE ON package_who_can_rent_choice (who_can_rent_choice_id)');
        $this->addSql('ALTER TABLE package_who_can_rent_choice ADD PRIMARY KEY (package_id, who_can_rent_choice_id)');
        $this->addSql('DROP INDEX idx_48ff341f44cabff ON package_who_can_rent_choice');
        $this->addSql('CREATE INDEX IDX_27443592F44CABFF ON package_who_can_rent_choice (package_id)');
        $this->addSql('ALTER TABLE package_who_can_rent_choice ADD CONSTRAINT FK_48FF341F44CABFF FOREIGN KEY (package_id) REFERENCES Package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Booking DROP FOREIGN KEY FK_2FB1D4425783CABD');
        $this->addSql('ALTER TABLE Booking DROP FOREIGN KEY FK_2FB1D442E6C5D2A3');
        $this->addSql('ALTER TABLE Booking DROP FOREIGN KEY FK_2FB1D442F742942');
        $this->addSql('ALTER TABLE Booking CHANGE name name VARCHAR(190) NOT NULL, CHANGE referenceNumber referenceNumber VARCHAR(190) NOT NULL, CHANGE renterHash renterHash VARCHAR(199) NOT NULL');
        $this->addSql('DROP INDEX idx_2fb1d442f742942 ON Booking');
        $this->addSql('CREATE INDEX IDX_2FB1D442BF6AC7F3 ON Booking (renting_privileges_id)');
        $this->addSql('DROP INDEX idx_2fb1d4425783cabd ON Booking');
        $this->addSql('CREATE INDEX IDX_2FB1D4426950F2D5 ON Booking (given_away_by_id)');
        $this->addSql('DROP INDEX idx_2fb1d442e6c5d2a3 ON Booking');
        $this->addSql('CREATE INDEX IDX_2FB1D4426F8DDD17 ON Booking (received_by_id)');
        $this->addSql('ALTER TABLE Booking ADD CONSTRAINT FK_2FB1D4425783CABD FOREIGN KEY (given_away_by_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE Booking ADD CONSTRAINT FK_2FB1D442E6C5D2A3 FOREIGN KEY (received_by_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE Booking ADD CONSTRAINT FK_2FB1D442F742942 FOREIGN KEY (renting_privileges_id) REFERENCES WhoCanRentChoice (id)');
        $this->addSql('ALTER TABLE Booking_audit ADD renting_privileges_id INT DEFAULT NULL, ADD given_away_by_id INT DEFAULT NULL, ADD received_by_id INT DEFAULT NULL, DROP rentingPrivileges_id, DROP givenAwayBy_id, DROP receivedBy_id, CHANGE name name VARCHAR(190) DEFAULT NULL, CHANGE referenceNumber referenceNumber VARCHAR(190) DEFAULT NULL, CHANGE renterHash renterHash VARCHAR(199) DEFAULT NULL, CHANGE `returning` return_date DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE File CHANGE tiedostoinfo tiedostoinfo VARCHAR(190) DEFAULT NULL');
        $this->addSql('ALTER TABLE Item CHANGE Name Name VARCHAR(190) NOT NULL, CHANGE Manufacturer Manufacturer VARCHAR(190) DEFAULT NULL, CHANGE Model Model VARCHAR(190) DEFAULT NULL, CHANGE SerialNumber SerialNumber VARCHAR(190) DEFAULT NULL, CHANGE PlaceInStorage PlaceInStorage VARCHAR(190) DEFAULT NULL, CHANGE History History VARCHAR(190) DEFAULT NULL');
        $this->addSql('ALTER TABLE item_who_can_rent_choice DROP FOREIGN KEY FK_EAB3B69AE9D9A436');
        $this->addSql('DROP INDEX IDX_EAB3B69AE9D9A436 ON item_who_can_rent_choice');
        $this->addSql('ALTER TABLE item_who_can_rent_choice DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE item_who_can_rent_choice DROP FOREIGN KEY FK_EAB3B69A126F525E');
        $this->addSql('ALTER TABLE item_who_can_rent_choice CHANGE whocanrentchoice_id who_can_rent_choice_id INT NOT NULL');
        $this->addSql('ALTER TABLE item_who_can_rent_choice ADD CONSTRAINT FK_4F9286AB44A2EEE FOREIGN KEY (who_can_rent_choice_id) REFERENCES WhoCanRentChoice (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_4F9286AB44A2EEE ON item_who_can_rent_choice (who_can_rent_choice_id)');
        $this->addSql('ALTER TABLE item_who_can_rent_choice ADD PRIMARY KEY (item_id, who_can_rent_choice_id)');
        $this->addSql('DROP INDEX idx_eab3b69a126f525e ON item_who_can_rent_choice');
        $this->addSql('CREATE INDEX IDX_4F9286A126F525E ON item_who_can_rent_choice (item_id)');
        $this->addSql('ALTER TABLE item_who_can_rent_choice ADD CONSTRAINT FK_EAB3B69A126F525E FOREIGN KEY (item_id) REFERENCES Item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Item_audit CHANGE Name Name VARCHAR(190) DEFAULT NULL, CHANGE Manufacturer Manufacturer VARCHAR(190) DEFAULT NULL, CHANGE Model Model VARCHAR(190) DEFAULT NULL, CHANGE SerialNumber SerialNumber VARCHAR(190) DEFAULT NULL, CHANGE PlaceInStorage PlaceInStorage VARCHAR(190) DEFAULT NULL, CHANGE History History VARCHAR(190) DEFAULT NULL');
        $this->addSql('ALTER TABLE Renter CHANGE name name VARCHAR(190) NOT NULL, CHANGE streetadress streetadress VARCHAR(190) DEFAULT NULL, CHANGE organization organization VARCHAR(190) DEFAULT NULL, CHANGE zipcode zipcode VARCHAR(190) DEFAULT NULL, CHANGE city city VARCHAR(190) DEFAULT NULL, CHANGE phone phone VARCHAR(190) DEFAULT NULL, CHANGE email email VARCHAR(190) DEFAULT NULL');
        $this->addSql('ALTER TABLE WhoCanRentChoice CHANGE name name VARCHAR(190) NOT NULL');
        $this->addSql('ALTER TABLE member CHANGE firstname firstname VARCHAR(190) NOT NULL, CHANGE email email VARCHAR(190) DEFAULT NULL, CHANGE phone phone VARCHAR(190) DEFAULT NULL, CHANGE CityOfResidence CityOfResidence VARCHAR(190) DEFAULT NULL, CHANGE lastname lastname VARCHAR(190) NOT NULL, CHANGE username username VARCHAR(190) DEFAULT NULL');
        $this->addSql('ALTER TABLE AccessoryChoice CHANGE name name VARCHAR(190) NOT NULL');
        $this->addSql('ALTER TABLE media__media DROP FOREIGN KEY FK_5C6DD74E12469DE2');
        $this->addSql('DROP INDEX IDX_5C6DD74E12469DE2 ON media__media');
        $this->addSql('ALTER TABLE media__media DROP category_id');
        $this->addSql('ALTER TABLE timeline__timeline DROP FOREIGN KEY FK_FFBC6AD523EDC87');
        $this->addSql('ALTER TABLE timeline__timeline DROP FOREIGN KEY FK_FFBC6AD59D32F035');
        $this->addSql('DROP INDEX IDX_FFBC6AD59D32F035 ON timeline__timeline');
        $this->addSql('DROP INDEX IDX_FFBC6AD523EDC87 ON timeline__timeline');
        $this->addSql('ALTER TABLE timeline__timeline DROP action_id, DROP subject_id');
        $this->addSql('ALTER TABLE timeline__action_component DROP FOREIGN KEY FK_6ACD1B169D32F035');
        $this->addSql('ALTER TABLE timeline__action_component DROP FOREIGN KEY FK_6ACD1B16E2ABAFFF');
        $this->addSql('DROP INDEX IDX_6ACD1B16E2ABAFFF ON timeline__action_component');
        $this->addSql('DROP INDEX IDX_6ACD1B169D32F035 ON timeline__action_component');
        $this->addSql('ALTER TABLE timeline__action_component DROP action_id, DROP component_id');
        $this->addSql('DROP INDEX idx_state ON notification__message');
        $this->addSql('DROP INDEX idx_created_at ON notification__message');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE AccessoryChoice_audit (id INT NOT NULL, rev INT NOT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, compensationPrice INT DEFAULT NULL, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_57afe5dcb4bc13809349b468d6b3cdf9_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE Accessory_audit (id INT NOT NULL, rev INT NOT NULL, name_id INT DEFAULT NULL, count VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_a0345c113ec838028cbe177945d497e8_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE BillableEvent_audit (id INT NOT NULL, rev INT NOT NULL, booking_id INT DEFAULT NULL, description LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, unitPrice NUMERIC(7, 2) DEFAULT NULL, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_273681e0d43a25c2740cbc482b068932_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE Event_audit (id INT NOT NULL, rev INT NOT NULL, item_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, Description VARCHAR(5000) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CreatedAt DATETIME DEFAULT NULL, UpdatedAt DATETIME DEFAULT NULL, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, booking_id INT DEFAULT NULL, INDEX rev_57b9919381962bdb8c354a66cec19c80_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE File_audit (id INT NOT NULL, rev INT NOT NULL, product_id INT DEFAULT NULL, file_id INT DEFAULT NULL, tiedostoinfo VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_3d323e3265ba8776d509385e025c6bdc_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE Package_audit (id INT NOT NULL, rev INT NOT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, rent VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, needs_fixing TINYINT(1) DEFAULT NULL, notes LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_9cd6d075b9a97cbe2a40554de24d10cf_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE Pakage_tags (item_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_DF84378126F525E (item_id), INDEX IDX_DF84378BAD26311 (tag_id), PRIMARY KEY(item_id, tag_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE Renter_audit (id INT NOT NULL, rev INT NOT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, streetadress VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, organization VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, zipcode VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, city VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, phone VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_5e840ad37ca8843b2557b22a6ca155aa_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE WhoCanRentChoice_audit (id INT NOT NULL, rev INT NOT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_3a746e904a82a47a268f7ef637a7c92f_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE acl_classes (id INT UNSIGNED AUTO_INCREMENT NOT NULL, class_type VARCHAR(200) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, UNIQUE INDEX UNIQ_69DD750638A36066 (class_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE acl_entries (id INT UNSIGNED AUTO_INCREMENT NOT NULL, class_id INT UNSIGNED NOT NULL, object_identity_id INT UNSIGNED DEFAULT NULL, security_identity_id INT UNSIGNED NOT NULL, field_name VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ace_order SMALLINT UNSIGNED NOT NULL, mask INT NOT NULL, granting TINYINT(1) NOT NULL, granting_strategy VARCHAR(30) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, audit_success TINYINT(1) NOT NULL, audit_failure TINYINT(1) NOT NULL, INDEX IDX_46C8B806EA000B103D9AB4A6DF9183C9 (class_id, object_identity_id, security_identity_id), INDEX IDX_46C8B806EA000B10 (class_id), INDEX IDX_46C8B8063D9AB4A6 (object_identity_id), UNIQUE INDEX UNIQ_46C8B806EA000B103D9AB4A64DEF17BCE4289BF4 (class_id, object_identity_id, field_name, ace_order), INDEX IDX_46C8B806DF9183C9 (security_identity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE acl_object_identities (id INT UNSIGNED AUTO_INCREMENT NOT NULL, parent_object_identity_id INT UNSIGNED DEFAULT NULL, class_id INT UNSIGNED NOT NULL, object_identifier VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, entries_inheriting TINYINT(1) NOT NULL, INDEX IDX_9407E54977FA751A (parent_object_identity_id), UNIQUE INDEX UNIQ_9407E5494B12AD6EA000B10 (object_identifier, class_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE acl_object_identity_ancestors (object_identity_id INT UNSIGNED NOT NULL, ancestor_id INT UNSIGNED NOT NULL, INDEX IDX_825DE2993D9AB4A6 (object_identity_id), INDEX IDX_825DE299C671CEA1 (ancestor_id), PRIMARY KEY(object_identity_id, ancestor_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE acl_security_identities (id INT UNSIGNED AUTO_INCREMENT NOT NULL, identifier VARCHAR(200) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, username TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_8835EE78772E836AF85E0677 (identifier, username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE classification__category_audit (id INT NOT NULL, rev INT NOT NULL, parent_id INT DEFAULT NULL, context VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, media_id INT DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, enabled TINYINT(1) DEFAULT NULL, slug VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, description VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, position INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_4725bc84db5356e6585cf5f842a76074_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE classification__collection_audit (id INT NOT NULL, rev INT NOT NULL, context VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, media_id INT DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, enabled TINYINT(1) DEFAULT NULL, slug VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, description VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_30c2a45a4e0bc156e9330793e9c979bb_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE classification__context_audit (id VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, rev INT NOT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, enabled TINYINT(1) DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_a13a4c1bb983bb0c771d1c3f946f20e8_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE classification__tag_audit (id INT NOT NULL, rev INT NOT NULL, context VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, enabled TINYINT(1) DEFAULT NULL, slug VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_8b50432c424afcd2a3e0c8bc06435ab9_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE file_item (file_id INT NOT NULL, item_id INT NOT NULL, INDEX IDX_96E74D7093CB796C (file_id), INDEX IDX_96E74D70126F525E (item_id), PRIMARY KEY(file_id, item_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE fos_user_group_audit (id INT NOT NULL, rev INT NOT NULL, name VARCHAR(180) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, roles LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci` COMMENT \'(DC2Type:array)\', revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_791eaf97b684af9208d1f1d958a5729e_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE fos_user_user_audit (id INT NOT NULL, rev INT NOT NULL, username VARCHAR(180) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, username_canonical VARCHAR(180) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, email VARCHAR(180) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, email_canonical VARCHAR(180) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, enabled TINYINT(1) DEFAULT NULL, salt VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, password VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci` COMMENT \'(DC2Type:array)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, date_of_birth DATETIME DEFAULT NULL, firstname VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, lastname VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, website VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, biography VARCHAR(1000) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, gender VARCHAR(1) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, locale VARCHAR(8) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, timezone VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, phone VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, facebook_uid VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, facebook_name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, facebook_data LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci` COMMENT \'(DC2Type:json)\', twitter_uid VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, twitter_name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, twitter_data LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci` COMMENT \'(DC2Type:json)\', gplus_uid VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, gplus_name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, gplus_data LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci` COMMENT \'(DC2Type:json)\', token VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, two_step_code VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, member_id INT DEFAULT NULL, INDEX rev_782dc0f82f289145b1d57ca1c16ae709_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE media__gallery_audit (id INT NOT NULL, rev INT NOT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, context VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, default_format VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, enabled TINYINT(1) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_1ab07bc767a1d240bce23cc5a6c72fe2_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE media__gallery_media_audit (id INT NOT NULL, rev INT NOT NULL, gallery_id INT DEFAULT NULL, media_id INT DEFAULT NULL, position INT DEFAULT NULL, enabled TINYINT(1) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_e37fe6790d24ff70dcc7da52631a2b6d_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE media__media_audit (id INT NOT NULL, rev INT NOT NULL, category_id INT DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, description TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, enabled TINYINT(1) DEFAULT NULL, provider_name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, provider_status INT DEFAULT NULL, provider_reference VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, provider_metadata LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci` COMMENT \'(DC2Type:json)\', width INT DEFAULT NULL, height INT DEFAULT NULL, length NUMERIC(10, 0) DEFAULT NULL, content_type VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, content_size INT DEFAULT NULL, copyright VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, author_name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, context VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, cdn_is_flushable TINYINT(1) DEFAULT NULL, cdn_flush_identifier VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, cdn_flush_at DATETIME DEFAULT NULL, cdn_status INT DEFAULT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_7e85041618e08087eb9a0547f7c4b521_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE member_audit (id INT NOT NULL, rev INT NOT NULL, firstname VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, phone VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CityOfResidence VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, CopiedAsUser TINYINT(1) DEFAULT NULL, StudentUnionMember TINYINT(1) DEFAULT NULL, Application LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ApplicationDate DATETIME DEFAULT NULL, ApplicationHandledDate DATETIME DEFAULT NULL, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, lastname VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, isActiveMember TINYINT(1) DEFAULT NULL, reject_reason LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, rejectReasonSent TINYINT(1) DEFAULT NULL, username VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, INDEX rev_8da62cdf7ba1ec3a5c6fc91d8d3e0961_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE notification__message_audit (id INT NOT NULL, rev INT NOT NULL, type VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, body LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci` COMMENT \'(DC2Type:json)\', state INT DEFAULT NULL, restart_count INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, started_at DATETIME DEFAULT NULL, completed_at DATETIME DEFAULT NULL, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_c4538c3c50f6a8490d335e056fbf31fe_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE page__block_audit (id INT NOT NULL, rev INT NOT NULL, parent_id INT DEFAULT NULL, page_id INT DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, type VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, settings LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci` COMMENT \'(DC2Type:json)\', enabled TINYINT(1) DEFAULT NULL, position INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_4d54ecce0ea63dcfd483ef70a2876376_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE page__page_audit (id INT NOT NULL, rev INT NOT NULL, site_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, target_id INT DEFAULT NULL, route_name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, page_alias VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, type VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, position INT DEFAULT NULL, enabled TINYINT(1) DEFAULT NULL, decorate TINYINT(1) DEFAULT NULL, edited TINYINT(1) DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, slug LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, url LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, custom_url LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, request_method VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, title VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, meta_keyword VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, meta_description VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, javascript LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, stylesheet LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, raw_headers LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, template VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_cf8cb5735c18de903ee042bedd9d2799_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE page__site_audit (id INT NOT NULL, rev INT NOT NULL, enabled TINYINT(1) DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, relative_path VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, host VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, enabled_from DATETIME DEFAULT NULL, enabled_to DATETIME DEFAULT NULL, is_default TINYINT(1) DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, locale VARCHAR(7) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, title VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, meta_keywords VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, meta_description VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_a1d10b78f6fa4c7c0378c908e96e076c_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE page__snapshot_audit (id INT NOT NULL, rev INT NOT NULL, site_id INT DEFAULT NULL, page_id INT DEFAULT NULL, route_name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, page_alias VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, type VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, position INT DEFAULT NULL, enabled TINYINT(1) DEFAULT NULL, decorate TINYINT(1) DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, url LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, parent_id INT DEFAULT NULL, target_id INT DEFAULT NULL, content LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci` COMMENT \'(DC2Type:json)\', publication_date_start DATETIME DEFAULT NULL, publication_date_end DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, revtype VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, INDEX rev_d73cb73200c3c37ade59e07f74dca559_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE Pakage_tags ADD CONSTRAINT FK_DF84378126F525E FOREIGN KEY (item_id) REFERENCES Package (id)');
        $this->addSql('ALTER TABLE Pakage_tags ADD CONSTRAINT FK_DF84378BAD26311 FOREIGN KEY (tag_id) REFERENCES classification__tag (id)');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B8063D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B806DF9183C9 FOREIGN KEY (security_identity_id) REFERENCES acl_security_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B806EA000B10 FOREIGN KEY (class_id) REFERENCES acl_classes (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_object_identities ADD CONSTRAINT FK_9407E54977FA751A FOREIGN KEY (parent_object_identity_id) REFERENCES acl_object_identities (id)');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors ADD CONSTRAINT FK_825DE2993D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors ADD CONSTRAINT FK_825DE299C671CEA1 FOREIGN KEY (ancestor_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE file_item ADD CONSTRAINT FK_96E74D70126F525E FOREIGN KEY (item_id) REFERENCES Item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE file_item ADD CONSTRAINT FK_96E74D7093CB796C FOREIGN KEY (file_id) REFERENCES File (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE AccessoryChoice CHANGE name name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`');
        $this->addSql('ALTER TABLE Booking DROP FOREIGN KEY FK_2FB1D442BF6AC7F3');
        $this->addSql('ALTER TABLE Booking DROP FOREIGN KEY FK_2FB1D4426950F2D5');
        $this->addSql('ALTER TABLE Booking DROP FOREIGN KEY FK_2FB1D4426F8DDD17');
        $this->addSql('ALTER TABLE Booking CHANGE name name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, CHANGE referenceNumber referenceNumber VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, CHANGE renterHash renterHash VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`');
        $this->addSql('DROP INDEX idx_2fb1d4426950f2d5 ON Booking');
        $this->addSql('CREATE INDEX IDX_2FB1D4425783CABD ON Booking (given_away_by_id)');
        $this->addSql('DROP INDEX idx_2fb1d442bf6ac7f3 ON Booking');
        $this->addSql('CREATE INDEX IDX_2FB1D442F742942 ON Booking (renting_privileges_id)');
        $this->addSql('DROP INDEX idx_2fb1d4426f8ddd17 ON Booking');
        $this->addSql('CREATE INDEX IDX_2FB1D442E6C5D2A3 ON Booking (received_by_id)');
        $this->addSql('ALTER TABLE Booking ADD CONSTRAINT FK_2FB1D442BF6AC7F3 FOREIGN KEY (renting_privileges_id) REFERENCES WhoCanRentChoice (id)');
        $this->addSql('ALTER TABLE Booking ADD CONSTRAINT FK_2FB1D4426950F2D5 FOREIGN KEY (given_away_by_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE Booking ADD CONSTRAINT FK_2FB1D4426F8DDD17 FOREIGN KEY (received_by_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE Booking_audit ADD rentingPrivileges_id INT DEFAULT NULL, ADD givenAwayBy_id INT DEFAULT NULL, ADD receivedBy_id INT DEFAULT NULL, DROP renting_privileges_id, DROP given_away_by_id, DROP received_by_id, CHANGE name name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE referenceNumber referenceNumber VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE renterHash renterHash VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE return_date `returning` DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE File CHANGE tiedostoinfo tiedostoinfo VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`');
        $this->addSql('ALTER TABLE Item CHANGE Name Name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, CHANGE Manufacturer Manufacturer VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE Model Model VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE SerialNumber SerialNumber VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE PlaceInStorage PlaceInStorage VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE History History VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`');
        $this->addSql('ALTER TABLE Item_audit CHANGE Name Name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE Manufacturer Manufacturer VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE Model Model VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE SerialNumber SerialNumber VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE PlaceInStorage PlaceInStorage VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE History History VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`');
        $this->addSql('ALTER TABLE Package CHANGE name name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, CHANGE rent rent VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`');
        $this->addSql('ALTER TABLE Renter CHANGE name name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, CHANGE streetadress streetadress VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE organization organization VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE zipcode zipcode VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE city city VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE phone phone VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE email email VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`');
        $this->addSql('ALTER TABLE WhoCanRentChoice CHANGE name name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`');
        $this->addSql('ALTER TABLE item_who_can_rent_choice DROP FOREIGN KEY FK_4F9286AB44A2EEE');
        $this->addSql('DROP INDEX IDX_4F9286AB44A2EEE ON item_who_can_rent_choice');
        $this->addSql('ALTER TABLE item_who_can_rent_choice DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE item_who_can_rent_choice DROP FOREIGN KEY FK_4F9286A126F525E');
        $this->addSql('ALTER TABLE item_who_can_rent_choice CHANGE who_can_rent_choice_id whocanrentchoice_id INT NOT NULL');
        $this->addSql('ALTER TABLE item_who_can_rent_choice ADD CONSTRAINT FK_EAB3B69AE9D9A436 FOREIGN KEY (whocanrentchoice_id) REFERENCES WhoCanRentChoice (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_EAB3B69AE9D9A436 ON item_who_can_rent_choice (whocanrentchoice_id)');
        $this->addSql('ALTER TABLE item_who_can_rent_choice ADD PRIMARY KEY (item_id, whocanrentchoice_id)');
        $this->addSql('DROP INDEX idx_4f9286a126f525e ON item_who_can_rent_choice');
        $this->addSql('CREATE INDEX IDX_EAB3B69A126F525E ON item_who_can_rent_choice (item_id)');
        $this->addSql('ALTER TABLE item_who_can_rent_choice ADD CONSTRAINT FK_4F9286A126F525E FOREIGN KEY (item_id) REFERENCES Item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE media__media ADD category_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE media__media ADD CONSTRAINT FK_5C6DD74E12469DE2 FOREIGN KEY (category_id) REFERENCES classification__category (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_5C6DD74E12469DE2 ON media__media (category_id)');
        $this->addSql('ALTER TABLE member CHANGE firstname firstname VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, CHANGE lastname lastname VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, CHANGE email email VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE username username VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE phone phone VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE CityOfResidence CityOfResidence VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`');
        $this->addSql('CREATE INDEX idx_state ON notification__message (state)');
        $this->addSql('CREATE INDEX idx_created_at ON notification__message (created_at)');
        $this->addSql('ALTER TABLE package_who_can_rent_choice DROP FOREIGN KEY FK_27443592B44A2EEE');
        $this->addSql('DROP INDEX IDX_27443592B44A2EEE ON package_who_can_rent_choice');
        $this->addSql('ALTER TABLE package_who_can_rent_choice DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE package_who_can_rent_choice DROP FOREIGN KEY FK_27443592F44CABFF');
        $this->addSql('ALTER TABLE package_who_can_rent_choice CHANGE who_can_rent_choice_id whocanrentchoice_id INT NOT NULL');
        $this->addSql('ALTER TABLE package_who_can_rent_choice ADD CONSTRAINT FK_48FF341E9D9A436 FOREIGN KEY (whocanrentchoice_id) REFERENCES WhoCanRentChoice (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_48FF341E9D9A436 ON package_who_can_rent_choice (whocanrentchoice_id)');
        $this->addSql('ALTER TABLE package_who_can_rent_choice ADD PRIMARY KEY (package_id, whocanrentchoice_id)');
        $this->addSql('DROP INDEX idx_27443592f44cabff ON package_who_can_rent_choice');
        $this->addSql('CREATE INDEX IDX_48FF341F44CABFF ON package_who_can_rent_choice (package_id)');
        $this->addSql('ALTER TABLE package_who_can_rent_choice ADD CONSTRAINT FK_27443592F44CABFF FOREIGN KEY (package_id) REFERENCES Package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timeline__action_component ADD action_id INT DEFAULT NULL, ADD component_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE timeline__action_component ADD CONSTRAINT FK_6ACD1B169D32F035 FOREIGN KEY (action_id) REFERENCES timeline__action (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timeline__action_component ADD CONSTRAINT FK_6ACD1B16E2ABAFFF FOREIGN KEY (component_id) REFERENCES timeline__component (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_6ACD1B16E2ABAFFF ON timeline__action_component (component_id)');
        $this->addSql('CREATE INDEX IDX_6ACD1B169D32F035 ON timeline__action_component (action_id)');
        $this->addSql('ALTER TABLE timeline__timeline ADD action_id INT DEFAULT NULL, ADD subject_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE timeline__timeline ADD CONSTRAINT FK_FFBC6AD523EDC87 FOREIGN KEY (subject_id) REFERENCES timeline__component (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timeline__timeline ADD CONSTRAINT FK_FFBC6AD59D32F035 FOREIGN KEY (action_id) REFERENCES timeline__action (id)');
        $this->addSql('CREATE INDEX IDX_FFBC6AD59D32F035 ON timeline__timeline (action_id)');
        $this->addSql('CREATE INDEX IDX_FFBC6AD523EDC87 ON timeline__timeline (subject_id)');
    }
}
