when@dev:
  web_profiler_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.php"
    prefix:
      fi: /_wdt
      en: /en/_wdt

  web_profiler_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.php"
    prefix:
      fi: /_profiler
      en: /en/_profiler
