doctrine_migrations:
   dir_name: '%kernel.project_dir%/src/Migrations'
   # TODO: update to
   #namespace: DoctrineMigrations
   #migrations_paths:
   #   'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
