knpu_oauth2_client:
    clients:
        mattermost:
            type: generic
            provider_class: App\Provider\Mattermost
            client_id: "%mattermost_client_id%"
            client_secret: "%mattermost_client_secret%"
            redirect_route: "%mattermost_redirect_route%"
            redirect_params: { }

            # whether to check OAuth2 "state": defaults to true
            # use_state: false
