security:
    encoders:
        App\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN]
        BOARD: [ROLE_SUPER_ADMIN]
        CONTENT:
            - ROLE_ADMIN
            - ROLE_ENTROPY_ADMIN_MENU_ALL
            - ROLE_ENTROPY_ADMIN_EVENT_EDIT
            - ROLE_ENTROPY_ADMIN_EVENT_LIST
            - ROLE_ENTROPY_ADMIN_EVENT_CREATE
            - ROLE_ENTROPY_ADMIN_EVENT_VIEW
            - ROLE_SONATA_PAGE_ADMIN_PAGE_ALL
            - ROLE_SONATA_PAGE_ADMIN_BLOCK_ALL
            - ROLE_SONATA_PAGE_ADMIN_SHARED_BLOCK_ALL
            - ROLE_SONATA_PAGE_ADMIN_SNAPSHOT_ALL
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_ALL
        MEMBERS:
            - ROLE_ADMIN
            - ROLE_ENTROPY_TUNKKI_ADMIN_MEMBER_EDIT
            - ROLE_ENTROPY_TUNKKI_ADMIN_MEMBER_LIST
            - ROLE_ENTROPY_TUNKKI_ADMIN_MEMBER_CREATE
            - ROLE_ENTROPY_TUNKKI_ADMIN_MEMBER_VIEW
            - ROLE_ADMIN_EMAIL_EDIT
            - ROLE_ADMIN_EMAIL_LIST
            - ROLE_ADMIN_EMAIL_VIEW
        REWARDS:
            - ROLE_ADMIN
            - ROLE_ENTROPY_ADMIN_REWARD_EDIT
            - ROLE_ENTROPY_ADMIN_REWARD_LIST
            - ROLE_ENTROPY_ADMIN_REWARD_VIEW
            - ROLE_ENTROPY_ADMIN_REWARD_EXPORT
        RENTERS:
            - ROLE_ADMIN
            - ROLE_SONATA_CLASSIFICATION_ADMIN_CATEGORY_ALL
            - ROLE_SONATA_CLASSIFICATION_ADMIN_TAG_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_PACKAGE_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_INVOICEE_EDIT
            - ROLE_ENTROPY_TUNKKI_ADMIN_INVOICEE_LIST
            - ROLE_ENTROPY_TUNKKI_ADMIN_INVOICEE_CREATE
            - ROLE_ENTROPY_TUNKKI_ADMIN_INVOICEE_VIEW
            - ROLE_ENTROPY_TUNKKI_ADMIN_BILLABLE_EVENT_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_ACCESSORY_CHOICES_LIST
            - ROLE_ENTROPY_TUNKKI_ADMIN_ACCESSORY_CHOICES_CREATE
            - ROLE_ENTROPY_TUNKKI_ADMIN_ACCESSORY_CHOICES_VIEW
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_ITEM_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_EVENT_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_FILE_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_RENTER_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_ACCESSORY_CHOICES_EDIT
            - ROLE_ENTROPY_TUNKKI_ADMIN_ACCESSORY_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_PACKAGE_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_WHO_CAN_RENT_CHOICE_EDIT
            - ROLE_ENTROPY_TUNKKI_ADMIN_WHO_CAN_RENT_CHOICE_LIST
            - ROLE_ENTROPY_TUNKKI_ADMIN_WHO_CAN_RENT_CHOICE_CREATE
            - ROLE_ENTROPY_TUNKKI_ADMIN_WHO_CAN_RENT_CHOICE_VIEW
            - ROLE_ENTROPY_TUNKKI_ADMIN_BOOKING_EDIT
            - ROLE_ENTROPY_TUNKKI_ADMIN_BOOKING_LIST
            - ROLE_ENTROPY_TUNKKI_ADMIN_BOOKING_CREATE
            - ROLE_ENTROPY_TUNKKI_ADMIN_BOOKING_VIEW
            - ROLE_ENTROPY_ADMIN_CONTRACT_EDIT
            - ROLE_ENTROPY_ADMIN_CONTRACT_LIST
            - ROLE_ENTROPY_ADMIN_CONTRACT_VIEW
            - ROLE_ENTROPY_TUNKKI_ADMIN_STATUSEVENT_EDIT
            - ROLE_ENTROPY_TUNKKI_ADMIN_STATUSEVENT_LIST
            - ROLE_ENTROPY_TUNKKI_ADMIN_STATUSEVENT_CREATE
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            #        api_token:
            #            pattern: ^/oauth/token$
            #            security: false
        api_me:
            pattern: ^/api/me
            security: true
            stateless: true
            oauth2: true        
        main:
            user_checker: security.user_checker
            pattern:            .*
            context:            user
            anonymous:          true
            switch_user:        true
            guard:
                entry_point: App\Security\LoginFormAuthenticator
                authenticators:
                    - App\Security\LoginFormAuthenticator
                    - App\Security\MattermostAuthenticator

            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

    access_control:
        - { path: ^/oauth$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/check.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/authorize, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/profile/door$, role: ROLE_USER_HOST, host: entropy\.fi$ }
          #- { path: ^/profiili/ovi$, role: ROLE_USER_HOST, host: entropy\.fi$ }
        - { path: ^/profile, role: ROLE_USER }
        - { path: ^/profiili, role: ROLE_USER }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
