security:
    encoders:
        #        FOS\UserBundle\Model\UserInterface: sha512
        App\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT, ROLE_SONATA_PAGE_ADMIN_BLOCK_EDIT]
        CONTENT:
            - ROLE_ADMIN
            - SONATA
            - ROLE_ENTROPY_ADMIN_MENU_ALL
            - ROLE_ENTROPY_ADMIN_EVENT_EDIT
            - ROLE_ENTROPY_ADMIN_EVENT_LIST
            - ROLE_ENTROPY_ADMIN_EVENT_CREATE
            - ROLE_ENTROPY_ADMIN_EVENT_VIEW
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_ALL
            - ROLE_SONATA_PAGE_ADMIN_BLOCK_ALL
            - ROLE_SONATA_PAGE_ADMIN_SHARED_BLOCK_ALL
            - ROLE_SONATA_PAGE_ADMIN_SNAPSHOT_ALL
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_ALL
        MEMBERS:
            - ROLE_ADMIN
            - ROLE_ENTROPY_TUNKKI_ADMIN_MEMBER_EDIT
            - ROLE_ENTROPY_TUNKKI_ADMIN_MEMBER_LIST
            - ROLE_ENTROPY_TUNKKI_ADMIN_MEMBER_CREATE
            - ROLE_ENTROPY_TUNKKI_ADMIN_MEMBER_VIEW
            - ROLE_ADMIN_EMAIL_EDIT
            - ROLE_ADMIN_EMAIL_LIST
            - ROLE_ADMIN_EMAIL_VIEW
        REWARDS:
            - ROLE_ADMIN
            - ROLE_ENTROPY_ADMIN_REWARD_EDIT
            - ROLE_ENTROPY_ADMIN_REWARD_LIST
            - ROLE_ENTROPY_ADMIN_REWARD_VIEW
            - ROLE_ENTROPY_ADMIN_REWARD_EXPORT
        RENTER:
            - ROLE_ADMIN
            - ROLE_SONATA_CLASSIFICATION_ADMIN_CATEGORY_ALL
            - ROLE_SONATA_CLASSIFICATION_ADMIN_TAG_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_PAKAGE_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_INVOICEE_EDIT
            - ROLE_ENTROPY_TUNKKI_ADMIN_INVOICEE_LIST
            - ROLE_ENTROPY_TUNKKI_ADMIN_INVOICEE_CREATE
            - ROLE_ENTROPY_TUNKKI_ADMIN_INVOICEE_VIEW
            - ROLE_ENTROPY_TUNKKI_ADMIN_BILLABLE_EVENT_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_ACCESSORY_CHOICES_LIST
            - ROLE_ENTROPY_TUNKKI_ADMIN_ACCESSORY_CHOICES_CREATE
            - ROLE_ENTROPY_TUNKKI_ADMIN_ACCESSORY_CHOICES_VIEW
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_ITEM_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_EVENT_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_FILE_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_RENTER_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_ACCESSORY_CHOICES_EDIT
            - ROLE_ENTROPY_TUNKKI_ADMIN_ACCESSORY_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_PACKAGE_ALL
            - ROLE_ENTROPY_TUNKKI_ADMIN_WHO_CAN_RENT_CHOICE_EDIT
            - ROLE_ENTROPY_TUNKKI_ADMIN_WHO_CAN_RENT_CHOICE_LIST
            - ROLE_ENTROPY_TUNKKI_ADMIN_WHO_CAN_RENT_CHOICE_CREATE
            - ROLE_ENTROPY_TUNKKI_ADMIN_WHO_CAN_RENT_CHOICE_VIEW
            - ROLE_ENTROPY_TUNKKI_ADMIN_BOOKING_EDIT
            - ROLE_ENTROPY_TUNKKI_ADMIN_BOOKING_LIST
            - ROLE_ENTROPY_TUNKKI_ADMIN_BOOKING_CREATE
            - ROLE_ENTROPY_TUNKKI_ADMIN_BOOKING_VIEW
            - ROLE_ENTROPY_ADMIN_CONTRACT_EDIT
            - ROLE_ENTROPY_ADMIN_CONTRACT_LIST
            - ROLE_ENTROPY_ADMIN_CONTRACT_VIEW
            - ROLE_ENTROPY_TUNKKI_ADMIN_STATUSEVENT_EDIT
            - ROLE_ENTROPY_TUNKKI_ADMIN_STATUSEVENT_LIST
            - ROLE_ENTROPY_TUNKKI_ADMIN_STATUSEVENT_CREATE
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            user_checker: security.user_checker
            pattern:            .*
            context:            user
#            form_login:
#                login_path:     /login
#                default_target_path: /profile
#                check_path:     /login_check
#                post_only:      true
#            logout:
#                path:           /logout
#                target:         /login
            anonymous:          true
            switch_user:        true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
                # where to redirect after logout
                # target: app_any_route

#        api:
#            pattern:            /api(.*)
#            context:            user
#            form_login:
#                provider:       fos_userbundle
#                login_path:     /admin/login
#                use_forward:    false
#                check_path:     /admin/login_check
#                failure_path:   null
#            logout:
#                path:           /admin/logout
#            anonymous:          true

    access_control:
        - { path: ^/oauth$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/check.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          #- { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
          #- { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: ROLE_USER }
        - { path: ^/profiili, role: ROLE_USER }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
#        - { path: ^/api/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
