sonata_seo:
  encoding: UTF-8
  page:
    title: Entropy
    separator: " | "
    default: sonata.seo.page.default
    metas:
      name:
        keywords: Entropy,Ry,Electornic,Music,Association,Culture
        description: Electronic music and culture association
        robots: index, follow
        viewport: width=device-width, initial-scale=1

      property:
        # Facebook application settings
        #'fb:app_id':          XXXXXX
        #'fb:admins':          admin1, admin2

        # Open Graph information
        # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
        "og:site_name": Entropy ry
        "og:description": Electronic music and culture association
        "og:image:height": 512px
        "og:image:widht": 512px
        "twitter:card": summary_large_image
        #
      http-equiv:
        "Content-Type": text/html; charset=utf-8
        "X-Ua-Compatible": IE=EDGE
      charset:
        UTF-8: ""

    head:
      "xmlns": http://www.w3.org/1999/xhtml
      "xmlns:og": http://opengraphprotocol.org/schema/
