fos_user:
    db_driver:      orm
    from_email:
        address: webmaster@entropy.fi
        sender_name: Entropy TunkkiAdmin
    firewall_name: main
    user_class: App\Entity\User
    group:
        group_class: App\Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

sonata_user:
    security_acl: false
    manager_type: orm
    class:
        user: App\Entity\User
        group: App\Application\Sonata\UserBundle\Entity\Group
    admin:
        user:
            class:          App\Admin\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle
        group:
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle
