sonata_block:
    context_manager: sonata.page.block.context_manager
    default_contexts: [sonata_page_bundle]

sonata_admin:
    assets:
        extra_javascripts:
            - bundles/sonatapage/sonata-page.back.min.js
        extra_stylesheets:
            - bundles/sonatapage/sonata-page.back.min.css

sonata_page:
    is_inline_edition_on:  false
    slugify_service: sonata.core.slugify.cocur
    multisite: host_with_path
    use_streamed_response: false
    hide_disabled_blocks: true
    router_auto_register:
        enabled: true
        priority: 150
    ignore_route_patterns:
        - ^(.*)admin(.*)   # ignore admin route, ie route containing 'admin'
        - ^_(.*)          # ignore symfony routes
    ignore_routes:
        - sonata_page_esi_cache
        - sonata_page_ssi_cache
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_page_cache_esi
        - sonata_cache_ssi
        - sonata_page_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_symfony
        - sonata_page_exceptions_list
        - sonata_page_exceptions_edit
        - sonata_cache_apc
        - sonata_media_gallery_index
        - sonata_media_gallery_view
        - sonata_media_view
        - sonata_media_download

    ignore_uri_patterns:
        - ^/admin\/   # ignore admin route, ie route containing 'admin'

    default_template: default
    templates:
        default:
            path: 'layout.html.twig'
            name: Default

            containers:
                header:
                    name: Header
                content:
                    name: Content
                footer:
                    name: Footer
            matrix:
                layout: |
                    TTTTTTTT
                    TTTTTTTT
                    CCCCCCCC
                    CCCCCCCC
                    CCCCCCCC
                    BBBBBBBB
                    BBBBBBBB

                mapping:
                    T: header
                    C: content
                    B: footer

        fix:
            path: 'fix.html.twig'
            name: 'Fix Page'
            containers:
                hero:
                    name: Hero
                content:
                    name: Content
            matrix:
                layout: |
                    HHHHHHHH
                    CCCCCCCC
                    CCCCCCCC
                    CCCCCCCC
                    CCCCCCCC

                mapping:
                    H: hero
                    C: content


    direct_publication: '%kernel.debug%'

    catch_exceptions:
        not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal:     [500]    # so you can use the same page for different http errors or specify specific page for each error
    assets:
        stylesheets:
            #- 'bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css'
            - 'bundles/sonataadmin/vendor/iCheck/skins/square/blue.css'
            - 'css/bs4/bootstrap.min.css'
            - 'css/front.css'
        javascripts:
            #- 'bundles/sonatacore/vendor/jquery/dist/jquery.min.js'
            #- 'bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js'
            - 'js/bs4/jquery-3.4.1.slim.min.js'
            - 'js/bs4/bootstrap.min.js'
            - 'js/bs4/popper.min.js'
            - 'bundles/sonataadmin/vendor/iCheck/icheck.min.js'
            - 'bundles/sonatapage/sonata-page.front.js'
            - 'js/front.js'


    class:
        page: 'App\Application\Sonata\PageBundle\Entity\Page'
        snapshot: 'App\Application\Sonata\PageBundle\Entity\Snapshot'
        block: 'App\Application\Sonata\PageBundle\Entity\Block'
        site: 'App\Application\Sonata\PageBundle\Entity\Site'
