sonata_classification:
    class:
        tag:          App\Entity\Sonata\SonataClassificationTag
        category:     App\Entity\Sonata\SonataClassificationCategory
        collection:   App\Entity\Sonata\SonataClassificationCollection
        context:      App\Entity\Sonata\SonataClassificationContext

          #    admin:
          #        tag:
          #            class:        Sonata\ClassificationBundle\Admin\TagAdmin
          #            controller:   SonataAdminBundle:CRUD
          #            translation:  SonataClassificationBundle
          #        category:
          #            class:        Sonata\ClassificationBundle\Admin\CategoryAdmin
          #            controller:   SonataClassificationBundle:CategoryAdmin
          #            translation:  SonataClassificationBundle
          #        collection:
          #            class:        Sonata\ClassificationBundle\Admin\CollectionAdmin
          #            controller:   SonataAdminBundle:CRUD
          #            translation:  SonataClassificationBundle
          #        context:
          #            class:        Sonata\ClassificationBundle\Admin\ContextAdmin
          #            controller:   SonataAdminBundle:CRUD
          #            translation:  SonataClassificationBundle
