sonata_classification:
    class:
        tag:          App\Application\Sonata\ClassificationBundle\Entity\Tag
        category:     App\Application\Sonata\ClassificationBundle\Entity\Category
        collection:   App\Application\Sonata\ClassificationBundle\Entity\Collection
        media:        App\Application\Sonata\MediaBundle\Entity\Media
        context:      App\Application\Sonata\ClassificationBundle\Entity\Context

    admin:
        tag:
            class:        Sonata\ClassificationBundle\Admin\TagAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle
        category:
            class:        Sonata\ClassificationBundle\Admin\CategoryAdmin
            controller:   SonataClassificationBundle:CategoryAdmin
            translation:  SonataClassificationBundle
        collection:
            class:        Sonata\ClassificationBundle\Admin\CollectionAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle
        context:
            class:        Sonata\ClassificationBundle\Admin\ContextAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle
