sonata_formatter:
  default_formatter: richhtml
  formatters:
    text:
      service: sonata.formatter.text.text
      extensions:
        - sonata.formatter.twig.control_flow
        - sonata.formatter.twig.gist
    richhtml:
      service: sonata.formatter.text.raw
      extensions:
        - sonata.formatter.twig.control_flow
        - sonata.formatter.twig.gist
        - sonata.formatter.twig.media
fos_ck_editor:
  default_config: default
  configs:
    default:
      versionCheck: false
      toolbar:
        "standard"
        #extraPlugins: "html5audio"
    simple:
      versionCheck: false
      toolbar: "basic"
sonata_admin:
  assets:
    extra_javascripts:
      - /bundles/fosckeditor/ckeditor.js
