fpt_stripe:
  credentials:
    publishable_key: "%env(STRIPE_PUBLISHABLE_KEY)%"
    secret_key: "%env(STRIPE_SECRET_KEY)%"
  webhook:
    check_signature: true
    signature_key: "%env(STRIPE_WEBHOOK_SIGNATURE_KEY)%"

when@dev:
  fpt_stripe:
    webhook:
      check_signature: false

when@test:
  fpt_stripe:
    webhook:
      check_signature: false
