twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - '@SonataForm/Form/datepicker.html.twig'
        - '@SonataFormatter/Form/formatter.html.twig'
        - 'bootstrap_4_layout.html.twig'
        - 'media_widgets.html.twig'
    globals:
        tunkki_img: '%env(MM_TUNKKI_IMG)%'
    date:
        format: j.n.Y, H:i
        timezone: Europe/Helsinki
