twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'SonataCoreBundle:Form:datepicker.html.twig'
        - '@SonataFormatter/Form/formatter.html.twig'    
