# Täysi conffi: https://sonata-project.org/bundles/media/master/doc/reference/advanced_configuration.html

sonata_media:
        # if you don't use default namespace configuration
        #class:
        #    media: MyVendor\MediaBundle\Entity\Media
        #    gallery: MyVendor\MediaBundle\Entity\Gallery
        #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.vimeo
                - sonata.media.provider.file
            formats:
                small: { width: 100 , quality: 90}
                big:   { width: 500 , quality: 100}
        item:  # the default context is mandatory
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                small: { width: 500 , quality: 90}
                big:   { width: 1200 , quality: 100}
        sonata_collection:
            providers:
              - sonata.media.provider.image

            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}

        sonata_category:
            providers:
              - sonata.media.provider.image

            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/
    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
 
#    providers:
#        file:
#            allowed_extensions: ['webm', 'mp4', 'pdf']
#            allowed_mime_types: ['video/webm', 'video/mp4']
