sonata_seo:
#    default:          sonata.seo.page.default
    encoding:         UTF-8
    page:
        title:            Nitro Project
        metas:
            name:
                keywords:             foo bar
                description:          The description
                robots:               index, follow

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       Nitro Project Sandbox
                'og:description':     A demo of the some rich bundles for your Symfony2 projects
                #
            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                'X-Ua-Compatible':      IE=EDGE
            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
