cmf_routing:
    chain:
        routers_by_id:
            sonata.page.router: 150
            router.default: 100

sonata_page:
    is_inline_edition_on:  false
    slugify_service:      sonata.core.slugify.native
    multisite: host 
    use_streamed_response: true # set the value to false in debug mode or if the reverse proxy does not handle streamed response
    ignore_route_patterns:
        - ^(.*)admin(.*)   # ignore admin route, ie route containing 'admin'
        - ^_(.*)          # ignore symfony routes
    hide_disabled_blocks: true
    ignore_routes:
        - sonata_page_esi_cache
        - sonata_page_ssi_cache
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_page_cache_esi
        - sonata_cache_ssi
        - sonata_page_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_symfony
        - sonata_page_exceptions_list
        - sonata_page_exceptions_edit
        - sonata_cache_apc
        - sonata_media_gallery_index
        - sonata_media_gallery_view
        - sonata_media_view
        - sonata_media_download

    ignore_uri_patterns:
        - ^/admin\/   # ignore admin route, ie route containing 'admin'
        - ^/api\/   # ignore admin route, ie route containing 'admin'

    page_defaults:
        homepage: {decorate: false} # disable decoration for homepage, key - is a page route
    default_page_service:  sonata.page.service.default
    default_template: default # template key from templates section, used as default for pages
    templates:
        default: 
            path: 'EntropyTunkkiBundle::layout.html.twig' 
            name: Default

            containers:
                header:
                    name: Header
                content:
                    name: Content
                footer:
                    name: Footer
            matrix:
                layout: |
                    TTTTTTTT
                    TTTTTTTT
                    CCCCCCCC
                    CCCCCCCC
                    CCCCCCCC
                    BBBBBBBB
                    BBBBBBBB

                mapping:
                    T: header
                    C: content
                    B: footer

        fix:
            path: 'EntropyTunkkiBundle::fix.html.twig' 
            name: 'Fix Page'
            containers:
                hero:
                    name: Hero
                content:
                    name: Content
            matrix:
                layout: |
                    HHHHHHHH
                    CCCCCCCC
                    CCCCCCCC
                    CCCCCCCC
                    CCCCCCCC

                mapping:
                    H: hero
                    C: content

    # manage the http errors
    catch_exceptions:
         not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
         fatal:     [500]    # so you can use the same page for different http errors or specify specific page for each error
    assets:
        stylesheets:
            - 'bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css'
            - 'bundles/sonataadmin/vendor/iCheck/skins/square/blue.css'
            - 'bundles/entropytunkki/css/front.css'
        javascripts:
            - 'bundles/sonatacore/vendor/jquery/dist/jquery.min.js'
            - 'bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js'
            - 'bundles/sonataadmin/vendor/iCheck/icheck.min.js'
            - 'bundles/sonatapage/sonata-page.front.js'
            - 'bundles/entropytunkki/js/front.js'
