imports:
    - { resource: '@SonataTranslationBundle/Resources/config/config.yml'}

sonata_translation:
    locales: [fi, en]
    default_locale: fi
    # here enable the types you need
    #    gedmo:
    #    enabled: false
#    phpcr:
#        enabled: true
