controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
entropy_event_responsible:
  path:
    en: /{year}/{slug}/nakkikone/responsible
    fi: /{year}/{slug}/nakkikone/vastuuhenkilo
  controller: App\Controller\EventSignUpController::responsible
  requirements:
    year: '\d+'
entropy_event_nakki_sign_up:
  path: /{year}/{slug}/nakkikone/{id}/signup
  controller: App\Controller\EventSignUpController::nakkiSignUp
  requirements:
    year: '\d+'
    id: '\d+'
entropy_event_nakki_cancel:
  path: /{year}/{slug}/nakkikone/{id}/cancel
  controller: App\Controller\EventSignUpController::nakkiCancel
  requirements:
    year: '\d+'
    id: '\d+'
entropy_event_slug_nakkikone:
  path: /{year}/{slug}/nakkikone
  controller: App\Controller\EventSignUpController::nakkikone
  requirements:
    year: '\d+'
entropy_event_slug_artist_signup:
  path:
    en: /{year}/{slug}/artist/signup
    fi: /{year}/{slug}/artisti/ilmottautuminen
  controller: App\Controller\EventSignUpController::artistSignUp
  requirements:
    year: '\d+'
entropy_event_rsvp:
  path: /{year}/{slug}/rsvp
  controller: App\Controller\EventSignUpController::RSVP
  requirements:
    year: '\d+'
entropy_artist_profile:
  path:
    en: /profile/artist
    fi: /profiili/artisti
  controller: App\Controller\ArtistController::index
entropy_artist_create:
  path:
    en: /profile/artist/create
    fi: /profiili/artisti/uusi
  controller: App\Controller\ArtistController::create
entropy_artist_edit:
  path:
    en: /profile/artist/{id}/edit
    fi: /profiili/artisti/{id}/muokkaa
  controller: App\Controller\ArtistController::edit
  requirements:
    id: '\d+'
entropy_artist_delete:
  path: /profile/artist/{id}/delete
  controller: App\Controller\ArtistController::delete
  requirements:
    id: '\d+'
_entropy_mattermost_auth:
  path: /oauth
  controller: App\Controller\MattermostAuthController::connectAction
_entropy_mattermost_check:
  path: /oauth/check
  controller: App\Controller\MattermostAuthController::connectCheckAction
_entropy_mattermost_check_ssl:
  path: /oauth/check
  controller: App\Controller\MattermostAuthController::connectCheckAction
  schemes: [https]
  #_member_form:
  #path:    /member/join
  #controller: App\Controller\MemberFormController:newMember
  #_active_member_form:
  #path:    /member/active
  #controller: App\Controller\MemberFormController:activeMember
#sonata_translation:
#resource: '@SonataTranslationBundle/Resources/config/routes.yaml'
