entropy_tunkki_booking_hash:
    path:     /booking/{bookingid}/renter/{renterid}/{hash}
    controller: App\Controller\RenterHashController:indexAction 
    requirements:
        bookingid: '\d+'
        renterid: '\d+'
entropy_event:
    path:     /event/{id}/
    controller: App\Controller\EventController:oneAction 
    requirements:
        id: '\d+'
entropy_events:
    path:     /events/
    controller: App\Controller\EventController:allAction 
    requirements:

_entropy_mattermost_auth:
    path:     /oauth
    controller: App\Controller\MattermostAuthController:connectAction
_entropy_mattermost_check:
    path:     /oauth/check
    controller: App\Controller\MattermostAuthController:connectCheckAction
_entropy_mattermost_check_ssl:
    path:     /oauth/check
    controller: App\Controller\MattermostAuthController:connectCheckAction
    schemes:  [https]
_member_form:
    path:    /member/join
    controller: App\Controller\MemberFormController:newMember
_active_member_form:
    path:    /member/active
    controller: App\Controller\MemberFormController:activeMember


    #sonata_translation:
    #resource: '@SonataTranslationBundle/Resources/config/routes.yaml'
