controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
_entropy_mattermost_auth:
  path: /oauth
  controller: App\Controller\MattermostAuthController::connectAction
_entropy_mattermost_check:
  path: /oauth/check
  controller: App\Controller\MattermostAuthController::connectCheckAction
_entropy_mattermost_check_ssl:
  path: /oauth/check
  controller: App\Controller\MattermostAuthController::connectCheckAction
  schemes: [https]
