entropy_tunkki_booking_hash:
    path:     /booking/{bookingid}/renter/{renterid}/{hash}
    controller: App\Controller\RenterHashController:indexAction 
    requirements:
        bookingid: '\d+'
        renterid: '\d+'
entropy_event:
    path:     /tapahtuma/{id}/
    controller: App\Controller\EventController:oneId 
    requirements:
        id: '\d+'
entropy_event_en:
    path:     /event/{id}/
    controller: App\Controller\EventController:oneId 
    requirements:
        id: '\d+'
entropy_event_slug:
    path:     /{year}/{slug}/
    controller: App\Controller\EventController:oneSlug
    requirements:
        year: '\d+'
entropy_event_slug_artist_signup:
    path: 
        en: /{year}/{slug}/signup
        fi: /{year}/{slug}/ilmottautuminen
    controller: App\Controller\EventController:artistSignUp
    requirements:
        year: '\d+'
entropy_user_dashboard:
    path:
        en: /dashboard/
        fi: /yleiskatsaus/
    controller: App\Controller\ProfileController:dashboard
entropy_profile:
    path:
        en: /profile/
        fi: /profiili/
    controller: App\Controller\ProfileController:index
entropy_artist_profile:
    path:
        en: /profile/artist
        fi: /profiili/artisti
    controller: App\Controller\ArtistController:index
entropy_profile_door:
    path:
        en: /profile/door
        fi: /profiili/ovi
    controller: App\Controller\ProfileController:door
entropy_profile_edit:
    path:
        en: /profile/edit
        fi: /profiili/muokkaa
    controller: App\Controller\ProfileController:edit
entropy_artist_create:
    path:
        en: /profile/artist/create
        fi: /profiili/artisti/uusi
    controller: App\Controller\ArtistController:create
entropy_profile_active_member:
    path:
        en: /profile/apply
        fi: /profiili/aktiiviksi
    controller: App\Controller\ProfileController:apply
entropy_artist_edit:
    path:
        en: /profile/artist/{id}/edit
        fi: /profiili/artisti/{id}/muokkaa
    controller: App\Controller\ArtistController:edit
    requirements:
        id: '\d+'
entropy_artist_delete:
    path: /profile/artist/{id}/delete
    controller: App\Controller\ArtistController:delete
    requirements:
        id: '\d+'
_entropy_mattermost_auth:
    path:     /oauth
    controller: App\Controller\MattermostAuthController:connectAction
_entropy_mattermost_check:
    path:     /oauth/check
    controller: App\Controller\MattermostAuthController:connectCheckAction
_entropy_mattermost_check_ssl:
    path:     /oauth/check
    controller: App\Controller\MattermostAuthController:connectCheckAction
    schemes:  [https]
    #_member_form:
    #path:    /member/join
    #controller: App\Controller\MemberFormController:newMember
    #_active_member_form:
    #path:    /member/active
    #controller: App\Controller\MemberFormController:activeMember


    #sonata_translation:
    #resource: '@SonataTranslationBundle/Resources/config/routes.yaml'
