entropy_tunkki_booking_hash:
    path:     /booking/{bookingid}/renter/{renterid}/{hash}
    controller: App\Controller\RenterHashController:indexAction 
    requirements:
        bookingid: '\d+'
        renterid: '\d+'

_entropy_mattermost_auth:
    path:     /oauth
    controller: App\Controller\MattermostAuthController:connectAction
_entropy_mattermost_check:
    path:     /oauth/check
    controller: App\Controller\MattermostAuthController:connectCheckAction
_entropy_mattermost_check_ssl:
    path:     /oauth/check
    controller: App\Controller\MattermostAuthController:connectCheckAction
    schemes:  [https]
_member_form:
    path:    /join
    controller: App\Controller\MemberFormController:new
