<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20221019104702 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE Accessory (id INT AUTO_INCREMENT NOT NULL, name_id INT DEFAULT NULL, count VARCHAR(50) NOT NULL, INDEX IDX_2340A7BF71179CD6 (name_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE AccessoryChoice (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(190) NOT NULL, compensationPrice INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BillableEvent (id INT AUTO_INCREMENT NOT NULL, booking_id INT DEFAULT NULL, description LONGTEXT NOT NULL, unitPrice NUMERIC(7, 2) NOT NULL, INDEX IDX_7FF8C1D3301C60 (booking_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Booking (id INT AUTO_INCREMENT NOT NULL, renting_privileges_id INT DEFAULT NULL, renter_id INT DEFAULT NULL, given_away_by_id INT DEFAULT NULL, received_by_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name VARCHAR(190) NOT NULL, referenceNumber VARCHAR(190) NOT NULL, renterHash VARCHAR(199) NOT NULL, renterConsent TINYINT(1) NOT NULL, itemsReturned TINYINT(1) NOT NULL, invoiceSent TINYINT(1) NOT NULL, paid TINYINT(1) NOT NULL, cancelled TINYINT(1) NOT NULL, retrieval DATETIME DEFAULT NULL, return_date DATETIME DEFAULT NULL, paid_date DATETIME DEFAULT NULL, actualPrice NUMERIC(7, 2) DEFAULT NULL, numberOfRentDays INT NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, booking_date DATE NOT NULL, reason_for_discount VARCHAR(255) DEFAULT NULL, renter_signature LONGTEXT DEFAULT NULL, INDEX IDX_2FB1D442BF6AC7F3 (renting_privileges_id), INDEX IDX_2FB1D442E289A545 (renter_id), INDEX IDX_2FB1D4426950F2D5 (given_away_by_id), INDEX IDX_2FB1D4426F8DDD17 (received_by_id), INDEX IDX_2FB1D44261220EA6 (creator_id), INDEX IDX_2FB1D442D079F553 (modifier_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE booking_item (booking_id INT NOT NULL, item_id INT NOT NULL, INDEX IDX_78A07503301C60 (booking_id), INDEX IDX_78A0750126F525E (item_id), PRIMARY KEY(booking_id, item_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE booking_package (booking_id INT NOT NULL, package_id INT NOT NULL, INDEX IDX_84D622B53301C60 (booking_id), INDEX IDX_84D622B5F44CABFF (package_id), PRIMARY KEY(booking_id, package_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE booking_accessory (booking_id INT NOT NULL, accessory_id INT NOT NULL, INDEX IDX_3283EE1F3301C60 (booking_id), INDEX IDX_3283EE1F27E8CC78 (accessory_id), PRIMARY KEY(booking_id, accessory_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE revisions (id INT AUTO_INCREMENT NOT NULL, timestamp DATETIME NOT NULL, username VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Booking_audit (id INT NOT NULL, rev INT NOT NULL, renting_privileges_id INT DEFAULT NULL, renter_id INT DEFAULT NULL, given_away_by_id INT DEFAULT NULL, received_by_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name VARCHAR(190) DEFAULT NULL, referenceNumber VARCHAR(190) DEFAULT NULL, renterHash VARCHAR(199) DEFAULT NULL, renterConsent TINYINT(1) DEFAULT NULL, itemsReturned TINYINT(1) DEFAULT NULL, invoiceSent TINYINT(1) DEFAULT NULL, paid TINYINT(1) DEFAULT NULL, cancelled TINYINT(1) DEFAULT NULL, retrieval DATETIME DEFAULT NULL, return_date DATETIME DEFAULT NULL, paid_date DATETIME DEFAULT NULL, actualPrice NUMERIC(7, 2) DEFAULT NULL, numberOfRentDays INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, modified_at DATETIME DEFAULT NULL, booking_date DATE DEFAULT NULL, reason_for_discount VARCHAR(255) DEFAULT NULL, renter_signature LONGTEXT DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_b0495a931e8f8e31a90ec3920ac00d97_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE booking_item_audit (booking_id INT NOT NULL, item_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_6dad32ab0ec1d63cd52478ceab886472_idx (rev), PRIMARY KEY(booking_id, item_id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE booking_package_audit (booking_id INT NOT NULL, package_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_826893407febabf0c08145ef83b9fdf0_idx (rev), PRIMARY KEY(booking_id, package_id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE booking_accessory_audit (booking_id INT NOT NULL, accessory_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_c69824926ddea4c5d0eba82a5c805a8e_idx (rev), PRIMARY KEY(booking_id, accessory_id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE File (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, file_id INT DEFAULT NULL, tiedostoinfo VARCHAR(190) DEFAULT NULL, INDEX IDX_2CAD992E4584665A (product_id), INDEX IDX_2CAD992E93CB796C (file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Item (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, Name VARCHAR(190) NOT NULL, Manufacturer VARCHAR(190) DEFAULT NULL, Model VARCHAR(190) DEFAULT NULL, Url VARCHAR(500) DEFAULT NULL, SerialNumber VARCHAR(190) DEFAULT NULL, PlaceInStorage VARCHAR(190) DEFAULT NULL, Description VARCHAR(4000) DEFAULT NULL, Rent NUMERIC(7, 2) DEFAULT NULL, compensationPrice NUMERIC(7, 2) DEFAULT NULL, RentNotice VARCHAR(5000) DEFAULT NULL, NeedsFixing TINYINT(1) NOT NULL, ToSpareParts TINYINT(1) NOT NULL, CannotBeRented TINYINT(1) NOT NULL, ForSale TINYINT(1) DEFAULT NULL, Commission DATETIME DEFAULT NULL, purchasePrice NUMERIC(7, 2) DEFAULT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, INDEX IDX_BF298A2012469DE2 (category_id), INDEX IDX_BF298A2061220EA6 (creator_id), INDEX IDX_BF298A20D079F553 (modifier_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item_who_can_rent_choice (item_id INT NOT NULL, who_can_rent_choice_id INT NOT NULL, INDEX IDX_4F9286A126F525E (item_id), INDEX IDX_4F9286AB44A2EEE (who_can_rent_choice_id), PRIMARY KEY(item_id, who_can_rent_choice_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Item_tags (item_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_257D527E126F525E (item_id), INDEX IDX_257D527EBAD26311 (tag_id), PRIMARY KEY(item_id, tag_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item_booking (item_id INT NOT NULL, booking_id INT NOT NULL, INDEX IDX_EB51CB8A126F525E (item_id), INDEX IDX_EB51CB8A3301C60 (booking_id), PRIMARY KEY(item_id, booking_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item_package (item_id INT NOT NULL, package_id INT NOT NULL, INDEX IDX_D53541C1126F525E (item_id), INDEX IDX_D53541C1F44CABFF (package_id), PRIMARY KEY(item_id, package_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Item_audit (id INT NOT NULL, rev INT NOT NULL, category_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, Name VARCHAR(190) DEFAULT NULL, Manufacturer VARCHAR(190) DEFAULT NULL, Model VARCHAR(190) DEFAULT NULL, Url VARCHAR(500) DEFAULT NULL, SerialNumber VARCHAR(190) DEFAULT NULL, PlaceInStorage VARCHAR(190) DEFAULT NULL, Description VARCHAR(4000) DEFAULT NULL, Rent NUMERIC(7, 2) DEFAULT NULL, compensationPrice NUMERIC(7, 2) DEFAULT NULL, RentNotice VARCHAR(5000) DEFAULT NULL, NeedsFixing TINYINT(1) DEFAULT NULL, ToSpareParts TINYINT(1) DEFAULT NULL, CannotBeRented TINYINT(1) DEFAULT NULL, ForSale TINYINT(1) DEFAULT NULL, Commission DATETIME DEFAULT NULL, purchasePrice NUMERIC(7, 2) DEFAULT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_3c5f2b55d694c80478a68bde1a0e8d59_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item_who_can_rent_choice_audit (item_id INT NOT NULL, who_can_rent_choice_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_8cf66f943eb8b37edcdc173cdd415544_idx (rev), PRIMARY KEY(item_id, who_can_rent_choice_id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Item_tags_audit (item_id INT NOT NULL, tag_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_3f42baaf4b9c0a3f950bc850464bf19d_idx (rev), PRIMARY KEY(item_id, tag_id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item_booking_audit (item_id INT NOT NULL, booking_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_a661a911851649749a3f8933c8374d44_idx (rev), PRIMARY KEY(item_id, booking_id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item_package_audit (item_id INT NOT NULL, package_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_00218f2eb7af6a761489ed026afab81c_idx (rev), PRIMARY KEY(item_id, package_id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Package (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(190) NOT NULL, rent VARCHAR(190) NOT NULL, needs_fixing TINYINT(1) NOT NULL, notes LONGTEXT DEFAULT NULL, compensation_price NUMERIC(10, 2) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE package_who_can_rent_choice (package_id INT NOT NULL, who_can_rent_choice_id INT NOT NULL, INDEX IDX_27443592F44CABFF (package_id), INDEX IDX_27443592B44A2EEE (who_can_rent_choice_id), PRIMARY KEY(package_id, who_can_rent_choice_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Renter (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(190) NOT NULL, streetadress VARCHAR(190) DEFAULT NULL, organization VARCHAR(190) DEFAULT NULL, zipcode VARCHAR(190) DEFAULT NULL, city VARCHAR(190) DEFAULT NULL, phone VARCHAR(190) DEFAULT NULL, email VARCHAR(190) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE StatusEvent (id INT AUTO_INCREMENT NOT NULL, item_id INT DEFAULT NULL, booking_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, Description VARCHAR(5000) DEFAULT NULL, CreatedAt DATETIME NOT NULL, UpdatedAt DATETIME NOT NULL, INDEX IDX_19D077FB126F525E (item_id), INDEX IDX_19D077FB3301C60 (booking_id), INDEX IDX_19D077FB61220EA6 (creator_id), INDEX IDX_19D077FBD079F553 (modifier_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE WhoCanRentChoice (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(190) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE access_groups (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', active TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE access_groups_user (access_groups_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_6A61C5565E842834 (access_groups_id), INDEX IDX_6A61C556A76ED395 (user_id), PRIMARY KEY(access_groups_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE artist (id INT AUTO_INCREMENT NOT NULL, member_id INT DEFAULT NULL, picture_id INT DEFAULT NULL, name VARCHAR(190) NOT NULL, genre VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, bio LONGTEXT DEFAULT NULL, hardware VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, bio_en LONGTEXT DEFAULT NULL, links LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', copy_for_archive TINYINT(1) DEFAULT NULL, UNIQUE INDEX UNIQ_15996875E237E06 (name), INDEX IDX_15996877597D3FE (member_id), INDEX IDX_1599687EE45BDBF (picture_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classification__category (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, context INT DEFAULT NULL, name VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, slug VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, position INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_43629B36727ACA70 (parent_id), INDEX IDX_43629B36E25D857E (context), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classification__collection (id INT AUTO_INCREMENT NOT NULL, context INT DEFAULT NULL, name VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, slug VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_A406B56AE25D857E (context), UNIQUE INDEX tag_collection (slug, context), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classification__context (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classification__tag (id INT AUTO_INCREMENT NOT NULL, context INT DEFAULT NULL, name VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, slug VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_CA57A1C7E25D857E (context), UNIQUE INDEX tag_context (slug, context), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contract (id INT AUTO_INCREMENT NOT NULL, content_fi LONGTEXT NOT NULL, updated_at DATETIME NOT NULL, purpose VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, content_en LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_E98F2859B887B3EB (purpose), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE door_log (id INT AUTO_INCREMENT NOT NULL, member_id INT NOT NULL, created_at DATETIME NOT NULL, message VARCHAR(255) DEFAULT NULL, INDEX IDX_D5DDED277597D3FE (member_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE email (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, subject VARCHAR(255) NOT NULL, body LONGTEXT NOT NULL, purpose VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, add_login_links_to_footer TINYINT(1) DEFAULT NULL, reply_to VARCHAR(255) DEFAULT NULL, INDEX IDX_E7927C7471F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event (id INT AUTO_INCREMENT NOT NULL, picture_id INT DEFAULT NULL, attachment_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, nimi VARCHAR(255) NOT NULL, event_date DATETIME NOT NULL, publish_date DATETIME NOT NULL, css LONGTEXT DEFAULT NULL, content LONGTEXT DEFAULT NULL, sisallys LONGTEXT DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, published TINYINT(1) NOT NULL, type VARCHAR(180) NOT NULL, epics VARCHAR(180) DEFAULT NULL, external_url TINYINT(1) NOT NULL, sticky TINYINT(1) NOT NULL, picture_position VARCHAR(255) NOT NULL, cancelled TINYINT(1) NOT NULL, links LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', updated_at DATETIME NOT NULL, until DATETIME DEFAULT NULL, rsvp_system_enabled TINYINT(1) DEFAULT NULL, nakkikone_enabled TINYINT(1) NOT NULL, nakki_info_fi LONGTEXT DEFAULT NULL, nakki_info_en LONGTEXT DEFAULT NULL, include_safer_space_guidelines TINYINT(1) DEFAULT NULL, header_theme VARCHAR(255) NOT NULL, stream_player_url VARCHAR(255) DEFAULT NULL, img_filter_color VARCHAR(255) DEFAULT NULL, img_filter_blend_mode VARCHAR(255) DEFAULT NULL, artist_sign_up_enabled TINYINT(1) DEFAULT NULL, artist_sign_up_end DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', artist_sign_up_start DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', web_meeting_url VARCHAR(255) DEFAULT NULL, show_artist_sign_up_only_for_logged_in_members TINYINT(1) DEFAULT NULL, ticket_count INT NOT NULL, tickets_enabled TINYINT(1) DEFAULT NULL, ticket_price INT DEFAULT NULL, ticket_info_fi LONGTEXT DEFAULT NULL, ticket_info_en LONGTEXT DEFAULT NULL, ticket_presale_start DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', ticket_presale_end DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ticket_presale_count INT NOT NULL, show_nakkikone_link_in_event TINYINT(1) DEFAULT NULL, require_nakki_bookings_to_be_different_times TINYINT(1) DEFAULT NULL, rsvp_only_to_active_members TINYINT(1) DEFAULT NULL, INDEX IDX_3BAE0AA7EE45BDBF (picture_id), INDEX IDX_3BAE0AA7464E68B (attachment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_artist_info (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, artist_id INT DEFAULT NULL, artist_clone_id INT DEFAULT NULL, set_length VARCHAR(255) DEFAULT NULL, start_time DATETIME DEFAULT NULL, wish_for_play_time VARCHAR(255) DEFAULT NULL, free_word LONGTEXT DEFAULT NULL, stage VARCHAR(255) DEFAULT NULL, INDEX IDX_DCBE644871F7E88B (event_id), INDEX IDX_DCBE6448B7970CF8 (artist_id), INDEX IDX_DCBE64488502DB41 (artist_clone_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media__gallery (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, context VARCHAR(64) NOT NULL, default_format VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, updated_at DATETIME NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media__gallery_item (id INT AUTO_INCREMENT NOT NULL, gallery_id INT DEFAULT NULL, media_id INT DEFAULT NULL, position INT NOT NULL, enabled TINYINT(1) NOT NULL, updated_at DATETIME NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_3238519A4E7AF8F (gallery_id), INDEX IDX_3238519AEA9FDD75 (media_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media__media (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, enabled TINYINT(1) NOT NULL, provider_name VARCHAR(255) NOT NULL, provider_status INT NOT NULL, provider_reference VARCHAR(255) NOT NULL, provider_metadata LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', width INT DEFAULT NULL, height INT DEFAULT NULL, length NUMERIC(10, 0) DEFAULT NULL, content_type VARCHAR(255) DEFAULT NULL, content_size INT DEFAULT NULL, copyright VARCHAR(255) DEFAULT NULL, author_name VARCHAR(255) DEFAULT NULL, context VARCHAR(64) DEFAULT NULL, cdn_is_flushable TINYINT(1) NOT NULL, cdn_flush_identifier VARCHAR(64) DEFAULT NULL, cdn_flush_at DATETIME DEFAULT NULL, cdn_status INT DEFAULT NULL, updated_at DATETIME NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member (id INT AUTO_INCREMENT NOT NULL, firstname VARCHAR(190) NOT NULL, lastname VARCHAR(190) NOT NULL, email VARCHAR(190) NOT NULL, username VARCHAR(190) DEFAULT NULL, phone VARCHAR(190) DEFAULT NULL, CityOfResidence VARCHAR(190) DEFAULT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, isActiveMember TINYINT(1) NOT NULL, rejectReasonSent TINYINT(1) NOT NULL, StudentUnionMember TINYINT(1) NOT NULL, Application LONGTEXT DEFAULT NULL, reject_reason LONGTEXT DEFAULT NULL, ApplicationDate DATETIME DEFAULT NULL, ApplicationHandledDate DATETIME DEFAULT NULL, accepted_as_honorary_member DATETIME DEFAULT NULL, is_full_member TINYINT(1) NOT NULL, locale VARCHAR(255) DEFAULT NULL, theme VARCHAR(255) DEFAULT NULL, deny_kerde_access TINYINT(1) DEFAULT NULL, UNIQUE INDEX UNIQ_70E4FA78E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE menu (id INT AUTO_INCREMENT NOT NULL, page_fi_id INT DEFAULT NULL, page_en_id INT DEFAULT NULL, root_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, label VARCHAR(180) NOT NULL, nimi VARCHAR(180) NOT NULL, url VARCHAR(180) DEFAULT NULL, enabled TINYINT(1) NOT NULL, lft INT NOT NULL, lvl INT NOT NULL, rgt INT NOT NULL, position INT NOT NULL, INDEX IDX_7D053A9369FF2E8D (page_fi_id), INDEX IDX_7D053A93B3886CE4 (page_en_id), INDEX IDX_7D053A9379066886 (root_id), INDEX IDX_7D053A93727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nakki (id INT AUTO_INCREMENT NOT NULL, definition_id INT NOT NULL, event_id INT NOT NULL, responsible_id INT DEFAULT NULL, start_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', end_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', nakki_interval VARCHAR(255) NOT NULL COMMENT \'(DC2Type:dateinterval)\', mattermost_channel VARCHAR(255) DEFAULT NULL, INDEX IDX_955FE106D11EA911 (definition_id), INDEX IDX_955FE10671F7E88B (event_id), INDEX IDX_955FE106602AD315 (responsible_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nakki_booking (id INT AUTO_INCREMENT NOT NULL, nakki_id INT NOT NULL, member_id INT DEFAULT NULL, event_id INT NOT NULL, start_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', end_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_13C2BAC5DE7D37DF (nakki_id), INDEX IDX_13C2BAC57597D3FE (member_id), INDEX IDX_13C2BAC571F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nakki_definition (id INT AUTO_INCREMENT NOT NULL, name_fi VARCHAR(255) NOT NULL, name_en VARCHAR(255) NOT NULL, description_fi LONGTEXT NOT NULL, description_en LONGTEXT NOT NULL, only_for_active_members TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE oauth2_access_token (identifier CHAR(80) NOT NULL, client VARCHAR(32) NOT NULL, expiry DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', user_identifier VARCHAR(128) DEFAULT NULL, scopes TEXT DEFAULT NULL COMMENT \'(DC2Type:oauth2_scope)\', revoked TINYINT(1) NOT NULL, INDEX IDX_454D9673C7440455 (client), PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE oauth2_authorization_code (identifier CHAR(80) NOT NULL, client VARCHAR(32) NOT NULL, expiry DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', user_identifier VARCHAR(128) DEFAULT NULL, scopes TEXT DEFAULT NULL COMMENT \'(DC2Type:oauth2_scope)\', revoked TINYINT(1) NOT NULL, INDEX IDX_509FEF5FC7440455 (client), PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE oauth2_client (identifier VARCHAR(32) NOT NULL, name VARCHAR(128) NOT NULL, secret VARCHAR(128) DEFAULT NULL, redirect_uris TEXT DEFAULT NULL COMMENT \'(DC2Type:oauth2_redirect_uri)\', grants TEXT DEFAULT NULL COMMENT \'(DC2Type:oauth2_grant)\', scopes TEXT DEFAULT NULL COMMENT \'(DC2Type:oauth2_scope)\', active TINYINT(1) NOT NULL, allow_plain_text_pkce TINYINT(1) DEFAULT 0 NOT NULL, PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE oauth2_refresh_token (identifier CHAR(80) NOT NULL, access_token CHAR(80) DEFAULT NULL, expiry DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', revoked TINYINT(1) NOT NULL, INDEX IDX_4DD90732B6A2DD68 (access_token), PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page__block (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, page_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, type VARCHAR(255) NOT NULL, settings LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', enabled TINYINT(1) DEFAULT NULL, position INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_66F58DA0727ACA70 (parent_id), INDEX IDX_66F58DA0C4663E4 (page_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page__page (id INT AUTO_INCREMENT NOT NULL, site_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, route_name VARCHAR(255) NOT NULL, page_alias VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, position INT NOT NULL, enabled TINYINT(1) NOT NULL, decorate TINYINT(1) NOT NULL, edited TINYINT(1) NOT NULL, name VARCHAR(255) NOT NULL, slug LONGTEXT DEFAULT NULL, url LONGTEXT DEFAULT NULL, custom_url LONGTEXT DEFAULT NULL, request_method VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, meta_keyword VARCHAR(255) DEFAULT NULL, meta_description VARCHAR(255) DEFAULT NULL, javascript LONGTEXT DEFAULT NULL, stylesheet LONGTEXT DEFAULT NULL, raw_headers LONGTEXT DEFAULT NULL, template VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_2FAE39EDF6BD1646 (site_id), INDEX IDX_2FAE39ED727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page__site (id INT AUTO_INCREMENT NOT NULL, enabled TINYINT(1) NOT NULL, name VARCHAR(255) NOT NULL, relative_path VARCHAR(255) DEFAULT NULL, host VARCHAR(255) NOT NULL, enabled_from DATETIME DEFAULT NULL, enabled_to DATETIME DEFAULT NULL, is_default TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, locale VARCHAR(7) DEFAULT NULL, title VARCHAR(64) DEFAULT NULL, meta_keywords VARCHAR(255) DEFAULT NULL, meta_description VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page__snapshot (id INT AUTO_INCREMENT NOT NULL, site_id INT DEFAULT NULL, page_id INT DEFAULT NULL, route_name VARCHAR(255) NOT NULL, page_alias VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, position INT NOT NULL, enabled TINYINT(1) NOT NULL, decorate TINYINT(1) NOT NULL, name VARCHAR(255) NOT NULL, url LONGTEXT DEFAULT NULL, parent_id INT DEFAULT NULL, content LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', publication_date_start DATETIME DEFAULT NULL, publication_date_end DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_3963EF9AF6BD1646 (site_id), INDEX IDX_3963EF9AC4663E4 (page_id), INDEX idx_snapshot_dates_enabled (publication_date_start, publication_date_end, enabled), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reset_password_request (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', expires_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_7CE748AA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reward (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, payment_handled_by_id INT DEFAULT NULL, reward NUMERIC(10, 2) DEFAULT NULL, paid TINYINT(1) NOT NULL, paid_date DATETIME DEFAULT NULL, updated_at DATETIME NOT NULL, weight INT NOT NULL, evenout NUMERIC(10, 2) DEFAULT NULL, INDEX IDX_4ED17253A76ED395 (user_id), INDEX IDX_4ED17253361A68D (payment_handled_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reward_booking (reward_id INT NOT NULL, booking_id INT NOT NULL, INDEX IDX_ABB1026E466ACA1 (reward_id), INDEX IDX_ABB10263301C60 (booking_id), PRIMARY KEY(reward_id, booking_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rsvp (id INT AUTO_INCREMENT NOT NULL, event_id INT NOT NULL, member_id INT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', email VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_9FA5CE4EE7927C74 (email), INDEX IDX_9FA5CE4E71F7E88B (event_id), INDEX IDX_9FA5CE4E7597D3FE (member_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ticket (id INT AUTO_INCREMENT NOT NULL, event_id INT NOT NULL, owner_id INT DEFAULT NULL, recommended_by_id INT DEFAULT NULL, price INT NOT NULL, reference_number INT DEFAULT NULL, status VARCHAR(255) NOT NULL, updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_97A0ADA371F7E88B (event_id), INDEX IDX_97A0ADA37E3C61F9 (owner_id), UNIQUE INDEX UNIQ_97A0ADA3D59A4918 (recommended_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, member_id INT DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, last_login DATETIME DEFAULT NULL, mattermost_id VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D6497597D3FE (member_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE Accessory ADD CONSTRAINT FK_2340A7BF71179CD6 FOREIGN KEY (name_id) REFERENCES AccessoryChoice (id)');
        $this->addSql('ALTER TABLE BillableEvent ADD CONSTRAINT FK_7FF8C1D3301C60 FOREIGN KEY (booking_id) REFERENCES Booking (id)');
        $this->addSql('ALTER TABLE Booking ADD CONSTRAINT FK_2FB1D442BF6AC7F3 FOREIGN KEY (renting_privileges_id) REFERENCES WhoCanRentChoice (id)');
        $this->addSql('ALTER TABLE Booking ADD CONSTRAINT FK_2FB1D442E289A545 FOREIGN KEY (renter_id) REFERENCES Renter (id)');
        $this->addSql('ALTER TABLE Booking ADD CONSTRAINT FK_2FB1D4426950F2D5 FOREIGN KEY (given_away_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE Booking ADD CONSTRAINT FK_2FB1D4426F8DDD17 FOREIGN KEY (received_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE Booking ADD CONSTRAINT FK_2FB1D44261220EA6 FOREIGN KEY (creator_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE Booking ADD CONSTRAINT FK_2FB1D442D079F553 FOREIGN KEY (modifier_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE booking_item ADD CONSTRAINT FK_78A07503301C60 FOREIGN KEY (booking_id) REFERENCES Booking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE booking_item ADD CONSTRAINT FK_78A0750126F525E FOREIGN KEY (item_id) REFERENCES Item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE booking_package ADD CONSTRAINT FK_84D622B53301C60 FOREIGN KEY (booking_id) REFERENCES Booking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE booking_package ADD CONSTRAINT FK_84D622B5F44CABFF FOREIGN KEY (package_id) REFERENCES Package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE booking_accessory ADD CONSTRAINT FK_3283EE1F3301C60 FOREIGN KEY (booking_id) REFERENCES Booking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE booking_accessory ADD CONSTRAINT FK_3283EE1F27E8CC78 FOREIGN KEY (accessory_id) REFERENCES Accessory (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Booking_audit ADD CONSTRAINT rev_b0495a931e8f8e31a90ec3920ac00d97_fk FOREIGN KEY (rev) REFERENCES revisions (id)');
        $this->addSql('ALTER TABLE File ADD CONSTRAINT FK_2CAD992E4584665A FOREIGN KEY (product_id) REFERENCES Item (id)');
        $this->addSql('ALTER TABLE File ADD CONSTRAINT FK_2CAD992E93CB796C FOREIGN KEY (file_id) REFERENCES media__media (id)');
        $this->addSql('ALTER TABLE Item ADD CONSTRAINT FK_BF298A2012469DE2 FOREIGN KEY (category_id) REFERENCES classification__category (id)');
        $this->addSql('ALTER TABLE Item ADD CONSTRAINT FK_BF298A2061220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Item ADD CONSTRAINT FK_BF298A20D079F553 FOREIGN KEY (modifier_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE item_who_can_rent_choice ADD CONSTRAINT FK_4F9286A126F525E FOREIGN KEY (item_id) REFERENCES Item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE item_who_can_rent_choice ADD CONSTRAINT FK_4F9286AB44A2EEE FOREIGN KEY (who_can_rent_choice_id) REFERENCES WhoCanRentChoice (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Item_tags ADD CONSTRAINT FK_257D527E126F525E FOREIGN KEY (item_id) REFERENCES Item (id)');
        $this->addSql('ALTER TABLE Item_tags ADD CONSTRAINT FK_257D527EBAD26311 FOREIGN KEY (tag_id) REFERENCES classification__tag (id)');
        $this->addSql('ALTER TABLE item_booking ADD CONSTRAINT FK_EB51CB8A126F525E FOREIGN KEY (item_id) REFERENCES Item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE item_booking ADD CONSTRAINT FK_EB51CB8A3301C60 FOREIGN KEY (booking_id) REFERENCES Booking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE item_package ADD CONSTRAINT FK_D53541C1126F525E FOREIGN KEY (item_id) REFERENCES Item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE item_package ADD CONSTRAINT FK_D53541C1F44CABFF FOREIGN KEY (package_id) REFERENCES Package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Item_audit ADD CONSTRAINT rev_3c5f2b55d694c80478a68bde1a0e8d59_fk FOREIGN KEY (rev) REFERENCES revisions (id)');
        $this->addSql('ALTER TABLE package_who_can_rent_choice ADD CONSTRAINT FK_27443592F44CABFF FOREIGN KEY (package_id) REFERENCES Package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE package_who_can_rent_choice ADD CONSTRAINT FK_27443592B44A2EEE FOREIGN KEY (who_can_rent_choice_id) REFERENCES WhoCanRentChoice (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE StatusEvent ADD CONSTRAINT FK_19D077FB126F525E FOREIGN KEY (item_id) REFERENCES Item (id)');
        $this->addSql('ALTER TABLE StatusEvent ADD CONSTRAINT FK_19D077FB3301C60 FOREIGN KEY (booking_id) REFERENCES Booking (id)');
        $this->addSql('ALTER TABLE StatusEvent ADD CONSTRAINT FK_19D077FB61220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE StatusEvent ADD CONSTRAINT FK_19D077FBD079F553 FOREIGN KEY (modifier_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE access_groups_user ADD CONSTRAINT FK_6A61C5565E842834 FOREIGN KEY (access_groups_id) REFERENCES access_groups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE access_groups_user ADD CONSTRAINT FK_6A61C556A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE artist ADD CONSTRAINT FK_15996877597D3FE FOREIGN KEY (member_id) REFERENCES member (id)');
        $this->addSql('ALTER TABLE artist ADD CONSTRAINT FK_1599687EE45BDBF FOREIGN KEY (picture_id) REFERENCES media__media (id)');
        $this->addSql('ALTER TABLE classification__category ADD CONSTRAINT FK_43629B36727ACA70 FOREIGN KEY (parent_id) REFERENCES classification__category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE classification__category ADD CONSTRAINT FK_43629B36E25D857E FOREIGN KEY (context) REFERENCES classification__context (id)');
        $this->addSql('ALTER TABLE classification__collection ADD CONSTRAINT FK_A406B56AE25D857E FOREIGN KEY (context) REFERENCES classification__context (id)');
        $this->addSql('ALTER TABLE classification__tag ADD CONSTRAINT FK_CA57A1C7E25D857E FOREIGN KEY (context) REFERENCES classification__context (id)');
        $this->addSql('ALTER TABLE door_log ADD CONSTRAINT FK_D5DDED277597D3FE FOREIGN KEY (member_id) REFERENCES member (id)');
        $this->addSql('ALTER TABLE email ADD CONSTRAINT FK_E7927C7471F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7EE45BDBF FOREIGN KEY (picture_id) REFERENCES media__media (id)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7464E68B FOREIGN KEY (attachment_id) REFERENCES media__media (id)');
        $this->addSql('ALTER TABLE event_artist_info ADD CONSTRAINT FK_DCBE644871F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE event_artist_info ADD CONSTRAINT FK_DCBE6448B7970CF8 FOREIGN KEY (artist_id) REFERENCES artist (id)');
        $this->addSql('ALTER TABLE event_artist_info ADD CONSTRAINT FK_DCBE64488502DB41 FOREIGN KEY (artist_clone_id) REFERENCES artist (id)');
        $this->addSql('ALTER TABLE media__gallery_item ADD CONSTRAINT FK_3238519A4E7AF8F FOREIGN KEY (gallery_id) REFERENCES media__gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE media__gallery_item ADD CONSTRAINT FK_3238519AEA9FDD75 FOREIGN KEY (media_id) REFERENCES media__media (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A9369FF2E8D FOREIGN KEY (page_fi_id) REFERENCES page__page (id)');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A93B3886CE4 FOREIGN KEY (page_en_id) REFERENCES page__page (id)');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A9379066886 FOREIGN KEY (root_id) REFERENCES menu (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A93727ACA70 FOREIGN KEY (parent_id) REFERENCES menu (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE nakki ADD CONSTRAINT FK_955FE106D11EA911 FOREIGN KEY (definition_id) REFERENCES nakki_definition (id)');
        $this->addSql('ALTER TABLE nakki ADD CONSTRAINT FK_955FE10671F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE nakki ADD CONSTRAINT FK_955FE106602AD315 FOREIGN KEY (responsible_id) REFERENCES member (id)');
        $this->addSql('ALTER TABLE nakki_booking ADD CONSTRAINT FK_13C2BAC5DE7D37DF FOREIGN KEY (nakki_id) REFERENCES nakki (id)');
        $this->addSql('ALTER TABLE nakki_booking ADD CONSTRAINT FK_13C2BAC57597D3FE FOREIGN KEY (member_id) REFERENCES member (id)');
        $this->addSql('ALTER TABLE nakki_booking ADD CONSTRAINT FK_13C2BAC571F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE oauth2_access_token ADD CONSTRAINT FK_454D9673C7440455 FOREIGN KEY (client) REFERENCES oauth2_client (identifier) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE oauth2_authorization_code ADD CONSTRAINT FK_509FEF5FC7440455 FOREIGN KEY (client) REFERENCES oauth2_client (identifier) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE oauth2_refresh_token ADD CONSTRAINT FK_4DD90732B6A2DD68 FOREIGN KEY (access_token) REFERENCES oauth2_access_token (identifier) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE page__block ADD CONSTRAINT FK_66F58DA0727ACA70 FOREIGN KEY (parent_id) REFERENCES page__block (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE page__block ADD CONSTRAINT FK_66F58DA0C4663E4 FOREIGN KEY (page_id) REFERENCES page__page (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE page__page ADD CONSTRAINT FK_2FAE39EDF6BD1646 FOREIGN KEY (site_id) REFERENCES page__site (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE page__page ADD CONSTRAINT FK_2FAE39ED727ACA70 FOREIGN KEY (parent_id) REFERENCES page__page (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE page__snapshot ADD CONSTRAINT FK_3963EF9AF6BD1646 FOREIGN KEY (site_id) REFERENCES page__site (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE page__snapshot ADD CONSTRAINT FK_3963EF9AC4663E4 FOREIGN KEY (page_id) REFERENCES page__page (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE reward ADD CONSTRAINT FK_4ED17253A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE reward ADD CONSTRAINT FK_4ED17253361A68D FOREIGN KEY (payment_handled_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE reward_booking ADD CONSTRAINT FK_ABB1026E466ACA1 FOREIGN KEY (reward_id) REFERENCES reward (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reward_booking ADD CONSTRAINT FK_ABB10263301C60 FOREIGN KEY (booking_id) REFERENCES Booking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rsvp ADD CONSTRAINT FK_9FA5CE4E71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE rsvp ADD CONSTRAINT FK_9FA5CE4E7597D3FE FOREIGN KEY (member_id) REFERENCES member (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA371F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA37E3C61F9 FOREIGN KEY (owner_id) REFERENCES member (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3D59A4918 FOREIGN KEY (recommended_by_id) REFERENCES member (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6497597D3FE FOREIGN KEY (member_id) REFERENCES member (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE Accessory DROP FOREIGN KEY FK_2340A7BF71179CD6');
        $this->addSql('ALTER TABLE BillableEvent DROP FOREIGN KEY FK_7FF8C1D3301C60');
        $this->addSql('ALTER TABLE Booking DROP FOREIGN KEY FK_2FB1D442BF6AC7F3');
        $this->addSql('ALTER TABLE Booking DROP FOREIGN KEY FK_2FB1D442E289A545');
        $this->addSql('ALTER TABLE Booking DROP FOREIGN KEY FK_2FB1D4426950F2D5');
        $this->addSql('ALTER TABLE Booking DROP FOREIGN KEY FK_2FB1D4426F8DDD17');
        $this->addSql('ALTER TABLE Booking DROP FOREIGN KEY FK_2FB1D44261220EA6');
        $this->addSql('ALTER TABLE Booking DROP FOREIGN KEY FK_2FB1D442D079F553');
        $this->addSql('ALTER TABLE booking_item DROP FOREIGN KEY FK_78A07503301C60');
        $this->addSql('ALTER TABLE booking_item DROP FOREIGN KEY FK_78A0750126F525E');
        $this->addSql('ALTER TABLE booking_package DROP FOREIGN KEY FK_84D622B53301C60');
        $this->addSql('ALTER TABLE booking_package DROP FOREIGN KEY FK_84D622B5F44CABFF');
        $this->addSql('ALTER TABLE booking_accessory DROP FOREIGN KEY FK_3283EE1F3301C60');
        $this->addSql('ALTER TABLE booking_accessory DROP FOREIGN KEY FK_3283EE1F27E8CC78');
        $this->addSql('ALTER TABLE Booking_audit DROP FOREIGN KEY rev_b0495a931e8f8e31a90ec3920ac00d97_fk');
        $this->addSql('ALTER TABLE File DROP FOREIGN KEY FK_2CAD992E4584665A');
        $this->addSql('ALTER TABLE File DROP FOREIGN KEY FK_2CAD992E93CB796C');
        $this->addSql('ALTER TABLE Item DROP FOREIGN KEY FK_BF298A2012469DE2');
        $this->addSql('ALTER TABLE Item DROP FOREIGN KEY FK_BF298A2061220EA6');
        $this->addSql('ALTER TABLE Item DROP FOREIGN KEY FK_BF298A20D079F553');
        $this->addSql('ALTER TABLE item_who_can_rent_choice DROP FOREIGN KEY FK_4F9286A126F525E');
        $this->addSql('ALTER TABLE item_who_can_rent_choice DROP FOREIGN KEY FK_4F9286AB44A2EEE');
        $this->addSql('ALTER TABLE Item_tags DROP FOREIGN KEY FK_257D527E126F525E');
        $this->addSql('ALTER TABLE Item_tags DROP FOREIGN KEY FK_257D527EBAD26311');
        $this->addSql('ALTER TABLE item_booking DROP FOREIGN KEY FK_EB51CB8A126F525E');
        $this->addSql('ALTER TABLE item_booking DROP FOREIGN KEY FK_EB51CB8A3301C60');
        $this->addSql('ALTER TABLE item_package DROP FOREIGN KEY FK_D53541C1126F525E');
        $this->addSql('ALTER TABLE item_package DROP FOREIGN KEY FK_D53541C1F44CABFF');
        $this->addSql('ALTER TABLE Item_audit DROP FOREIGN KEY rev_3c5f2b55d694c80478a68bde1a0e8d59_fk');
        $this->addSql('ALTER TABLE package_who_can_rent_choice DROP FOREIGN KEY FK_27443592F44CABFF');
        $this->addSql('ALTER TABLE package_who_can_rent_choice DROP FOREIGN KEY FK_27443592B44A2EEE');
        $this->addSql('ALTER TABLE StatusEvent DROP FOREIGN KEY FK_19D077FB126F525E');
        $this->addSql('ALTER TABLE StatusEvent DROP FOREIGN KEY FK_19D077FB3301C60');
        $this->addSql('ALTER TABLE StatusEvent DROP FOREIGN KEY FK_19D077FB61220EA6');
        $this->addSql('ALTER TABLE StatusEvent DROP FOREIGN KEY FK_19D077FBD079F553');
        $this->addSql('ALTER TABLE access_groups_user DROP FOREIGN KEY FK_6A61C5565E842834');
        $this->addSql('ALTER TABLE access_groups_user DROP FOREIGN KEY FK_6A61C556A76ED395');
        $this->addSql('ALTER TABLE artist DROP FOREIGN KEY FK_15996877597D3FE');
        $this->addSql('ALTER TABLE artist DROP FOREIGN KEY FK_1599687EE45BDBF');
        $this->addSql('ALTER TABLE classification__category DROP FOREIGN KEY FK_43629B36727ACA70');
        $this->addSql('ALTER TABLE classification__category DROP FOREIGN KEY FK_43629B36E25D857E');
        $this->addSql('ALTER TABLE classification__collection DROP FOREIGN KEY FK_A406B56AE25D857E');
        $this->addSql('ALTER TABLE classification__tag DROP FOREIGN KEY FK_CA57A1C7E25D857E');
        $this->addSql('ALTER TABLE door_log DROP FOREIGN KEY FK_D5DDED277597D3FE');
        $this->addSql('ALTER TABLE email DROP FOREIGN KEY FK_E7927C7471F7E88B');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA7EE45BDBF');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA7464E68B');
        $this->addSql('ALTER TABLE event_artist_info DROP FOREIGN KEY FK_DCBE644871F7E88B');
        $this->addSql('ALTER TABLE event_artist_info DROP FOREIGN KEY FK_DCBE6448B7970CF8');
        $this->addSql('ALTER TABLE event_artist_info DROP FOREIGN KEY FK_DCBE64488502DB41');
        $this->addSql('ALTER TABLE media__gallery_item DROP FOREIGN KEY FK_3238519A4E7AF8F');
        $this->addSql('ALTER TABLE media__gallery_item DROP FOREIGN KEY FK_3238519AEA9FDD75');
        $this->addSql('ALTER TABLE menu DROP FOREIGN KEY FK_7D053A9369FF2E8D');
        $this->addSql('ALTER TABLE menu DROP FOREIGN KEY FK_7D053A93B3886CE4');
        $this->addSql('ALTER TABLE menu DROP FOREIGN KEY FK_7D053A9379066886');
        $this->addSql('ALTER TABLE menu DROP FOREIGN KEY FK_7D053A93727ACA70');
        $this->addSql('ALTER TABLE nakki DROP FOREIGN KEY FK_955FE106D11EA911');
        $this->addSql('ALTER TABLE nakki DROP FOREIGN KEY FK_955FE10671F7E88B');
        $this->addSql('ALTER TABLE nakki DROP FOREIGN KEY FK_955FE106602AD315');
        $this->addSql('ALTER TABLE nakki_booking DROP FOREIGN KEY FK_13C2BAC5DE7D37DF');
        $this->addSql('ALTER TABLE nakki_booking DROP FOREIGN KEY FK_13C2BAC57597D3FE');
        $this->addSql('ALTER TABLE nakki_booking DROP FOREIGN KEY FK_13C2BAC571F7E88B');
        $this->addSql('ALTER TABLE oauth2_access_token DROP FOREIGN KEY FK_454D9673C7440455');
        $this->addSql('ALTER TABLE oauth2_authorization_code DROP FOREIGN KEY FK_509FEF5FC7440455');
        $this->addSql('ALTER TABLE oauth2_refresh_token DROP FOREIGN KEY FK_4DD90732B6A2DD68');
        $this->addSql('ALTER TABLE page__block DROP FOREIGN KEY FK_66F58DA0727ACA70');
        $this->addSql('ALTER TABLE page__block DROP FOREIGN KEY FK_66F58DA0C4663E4');
        $this->addSql('ALTER TABLE page__page DROP FOREIGN KEY FK_2FAE39EDF6BD1646');
        $this->addSql('ALTER TABLE page__page DROP FOREIGN KEY FK_2FAE39ED727ACA70');
        $this->addSql('ALTER TABLE page__snapshot DROP FOREIGN KEY FK_3963EF9AF6BD1646');
        $this->addSql('ALTER TABLE page__snapshot DROP FOREIGN KEY FK_3963EF9AC4663E4');
        $this->addSql('ALTER TABLE reset_password_request DROP FOREIGN KEY FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE reward DROP FOREIGN KEY FK_4ED17253A76ED395');
        $this->addSql('ALTER TABLE reward DROP FOREIGN KEY FK_4ED17253361A68D');
        $this->addSql('ALTER TABLE reward_booking DROP FOREIGN KEY FK_ABB1026E466ACA1');
        $this->addSql('ALTER TABLE reward_booking DROP FOREIGN KEY FK_ABB10263301C60');
        $this->addSql('ALTER TABLE rsvp DROP FOREIGN KEY FK_9FA5CE4E71F7E88B');
        $this->addSql('ALTER TABLE rsvp DROP FOREIGN KEY FK_9FA5CE4E7597D3FE');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA371F7E88B');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA37E3C61F9');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA3D59A4918');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6497597D3FE');
        $this->addSql('DROP TABLE Accessory');
        $this->addSql('DROP TABLE AccessoryChoice');
        $this->addSql('DROP TABLE BillableEvent');
        $this->addSql('DROP TABLE Booking');
        $this->addSql('DROP TABLE booking_item');
        $this->addSql('DROP TABLE booking_package');
        $this->addSql('DROP TABLE booking_accessory');
        $this->addSql('DROP TABLE revisions');
        $this->addSql('DROP TABLE Booking_audit');
        $this->addSql('DROP TABLE booking_item_audit');
        $this->addSql('DROP TABLE booking_package_audit');
        $this->addSql('DROP TABLE booking_accessory_audit');
        $this->addSql('DROP TABLE File');
        $this->addSql('DROP TABLE Item');
        $this->addSql('DROP TABLE item_who_can_rent_choice');
        $this->addSql('DROP TABLE Item_tags');
        $this->addSql('DROP TABLE item_booking');
        $this->addSql('DROP TABLE item_package');
        $this->addSql('DROP TABLE Item_audit');
        $this->addSql('DROP TABLE item_who_can_rent_choice_audit');
        $this->addSql('DROP TABLE Item_tags_audit');
        $this->addSql('DROP TABLE item_booking_audit');
        $this->addSql('DROP TABLE item_package_audit');
        $this->addSql('DROP TABLE Package');
        $this->addSql('DROP TABLE package_who_can_rent_choice');
        $this->addSql('DROP TABLE Renter');
        $this->addSql('DROP TABLE StatusEvent');
        $this->addSql('DROP TABLE WhoCanRentChoice');
        $this->addSql('DROP TABLE access_groups');
        $this->addSql('DROP TABLE access_groups_user');
        $this->addSql('DROP TABLE artist');
        $this->addSql('DROP TABLE classification__category');
        $this->addSql('DROP TABLE classification__collection');
        $this->addSql('DROP TABLE classification__context');
        $this->addSql('DROP TABLE classification__tag');
        $this->addSql('DROP TABLE contract');
        $this->addSql('DROP TABLE door_log');
        $this->addSql('DROP TABLE email');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE event_artist_info');
        $this->addSql('DROP TABLE media__gallery');
        $this->addSql('DROP TABLE media__gallery_item');
        $this->addSql('DROP TABLE media__media');
        $this->addSql('DROP TABLE member');
        $this->addSql('DROP TABLE menu');
        $this->addSql('DROP TABLE nakki');
        $this->addSql('DROP TABLE nakki_booking');
        $this->addSql('DROP TABLE nakki_definition');
        $this->addSql('DROP TABLE oauth2_access_token');
        $this->addSql('DROP TABLE oauth2_authorization_code');
        $this->addSql('DROP TABLE oauth2_client');
        $this->addSql('DROP TABLE oauth2_refresh_token');
        $this->addSql('DROP TABLE page__block');
        $this->addSql('DROP TABLE page__page');
        $this->addSql('DROP TABLE page__site');
        $this->addSql('DROP TABLE page__snapshot');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE reward');
        $this->addSql('DROP TABLE reward_booking');
        $this->addSql('DROP TABLE rsvp');
        $this->addSql('DROP TABLE ticket');
        $this->addSql('DROP TABLE user');
    }
}
